"""
Structural Preprocessing Output Models
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any


@dataclass
class TissueSegmentationResult:
    """Tissue probability & segmentation volumes."""
    csf_volume_mm3: float
    gm_volume_mm3: float
    wm_volume_mm3: float
    total_brain_volume_mm3: float
    csf_fraction: float
    gm_fraction: float
    wm_fraction: float
    segmentation_artifact_sha256: str


@dataclass
class SpatialRegistrationResult:
    """Subject to MNI152NLin2009cAsym spatial registration."""
    template_name: str  # MNI152NLin2009cAsym
    forward_affine: List[List[float]]  # 4x4 affine matrix
    forward_warp_sha256: str
    inverse_warp_sha256: str
    dice_overlap: float
    mutual_information: float


@dataclass
class StructuralOutputs:
    """Outputs generated by the T1w structural preprocessing stage."""
    bias_corrected_t1w_path: str
    bias_corrected_t1w_sha256: str
    brain_mask_path: str
    brain_mask_sha256: str
    segmentation: TissueSegmentationResult
    registration: SpatialRegistrationResult
