/**
 * @magniom/web - Comprehensive Route Integrity & 404 Prevention Test Suite
 * Conforms to MAGNIOM-Application Shell, Navigation & Clinical Context Specification v2.0 (§190–§198).
 *
 * Requirements:
 * - Zero "404 — Destination Not Found" errors across any indication module navigation route.
 * - 100% route completeness across all 13 Canonical Golden Cases and all 8 Indication Modules.
 * - Automated verification that every path generated by getModuleUiDescriptor and deriveModuleWorkflow
 *   resolves to an active Next.js App Router page.
 */

import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { ALL_UX_GOLDEN_CASES_V2 } from '@magniom/test-fixtures';
import { getModuleUiDescriptor, deriveModuleWorkflow } from '@magniom/presentation';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const webAppRoot = path.resolve(__dirname, '..');
const appDir = path.join(webAppRoot, 'src', 'app');

/**
 * Maps a dynamic runtime URL path to the corresponding Next.js filesystem page path.
 */
function resolveUrlToPageFile(urlPath: string): string | null {
  // Strip query string and trailing slash
  const cleanPath = urlPath.split('?')[0]!.replace(/\/$/, '') || '/';

  // Check exact static route first
  const staticCandidate = path.join(appDir, cleanPath, 'page.tsx');
  if (fs.existsSync(staticCandidate)) {
    return staticCandidate;
  }

  // Handle /validation/studies/[studyId]
  if (cleanPath.startsWith('/validation/studies/')) {
    const segments = cleanPath.split('/').filter(Boolean);
    if (segments.length === 3) {
      const file = path.join(appDir, 'validation', 'studies', '[studyId]', 'page.tsx');
      return fs.existsSync(file) ? file : null;
    }
  }

  // Handle /cases/[caseId]/...
  if (cleanPath.startsWith('/cases/')) {
    const segments = cleanPath.split('/').filter(Boolean); // ['cases', caseId, ...]
    if (segments.length === 2) {
      // /cases/[caseId]
      const file = path.join(appDir, 'cases', '[caseId]', 'page.tsx');
      return fs.existsSync(file) ? file : null;
    }

    // /cases/[caseId]/measurements/[modality]
    if (segments.length === 4 && segments[2] === 'measurements') {
      const file = path.join(appDir, 'cases', '[caseId]', 'measurements', '[modality]', 'page.tsx');
      return fs.existsSync(file) ? file : null;
    }

    // /cases/[caseId]/indications/[caseIndicationId]/...
    if (segments[2] === 'indications') {
      if (segments.length === 3) {
        // /cases/[caseId]/indications
        const file = path.join(appDir, 'cases', '[caseId]', 'indications', 'page.tsx');
        return fs.existsSync(file) ? file : null;
      }
      if (segments.length === 4) {
        // /cases/[caseId]/indications/[caseIndicationId]
        const file = path.join(
          appDir,
          'cases',
          '[caseId]',
          'indications',
          '[caseIndicationId]',
          'page.tsx',
        );
        return fs.existsSync(file) ? file : null;
      }
      if (segments.length === 5) {
        // /cases/[caseId]/indications/[caseIndicationId]/[subSection]
        const subSection = segments[4];
        const file = path.join(
          appDir,
          'cases',
          '[caseId]',
          'indications',
          '[caseIndicationId]',
          subSection!,
          'page.tsx',
        );
        return fs.existsSync(file) ? file : null;
      }
    }

    // /cases/[caseId]/[subRoute]
    if (segments.length === 3) {
      const subRoute = segments[2];
      const file = path.join(appDir, 'cases', '[caseId]', subRoute!, 'page.tsx');
      return fs.existsSync(file) ? file : null;
    }
  }

  // Handle /research/cases/[caseId]/indications/[caseIndicationId]
  if (cleanPath.startsWith('/research/cases/')) {
    const segments = cleanPath.split('/').filter(Boolean);
    if (segments.length === 3) {
      // /research/cases/[caseId]
      const file = path.join(appDir, 'research', 'cases', '[caseId]', 'page.tsx');
      return fs.existsSync(file) ? file : null;
    }
    if (segments.length === 5 && segments[3] === 'indications') {
      const file = path.join(
        appDir,
        'research',
        'cases',
        '[caseId]',
        'indications',
        '[caseIndicationId]',
        'page.tsx',
      );
      return fs.existsSync(file) ? file : null;
    }
  }

  return null;
}

describe('MAGNIOM v2.0 Route Integrity & 404 Elimination Audit', () => {
  it('verifies that all 13 Golden Cases generate 100% valid, existing routes for context and measurements across all indications', () => {
    const failures: Array<{ caseId: string; indication: string; missingUrl: string }> = [];

    for (const bundle of ALL_UX_GOLDEN_CASES_V2) {
      const caseId = bundle.id;

      // Gather all indications on this case (primary + secondary/comorbid)
      const indicationCodes = bundle.availableIndications
        ? bundle.availableIndications.map(i => i.indicationCode)
        : [bundle.indicationCode];

      for (const indicationCode of indicationCodes) {
        const descriptor = getModuleUiDescriptor(indicationCode);

        // 1. Audit all context section routes
        for (const cs of descriptor.context_sections) {
          const url = `/cases/${caseId}/${cs.pathSuffix}`;
          const resolvedPage = resolveUrlToPageFile(url);
          if (!resolvedPage) {
            failures.push({ caseId, indication: indicationCode, missingUrl: url });
          }
        }

        // 2. Audit all measurement section routes
        for (const ms of descriptor.measurement_sections) {
          const url = `/cases/${caseId}/${ms.pathSuffix}`;
          const resolvedPage = resolveUrlToPageFile(url);
          if (!resolvedPage) {
            failures.push({ caseId, indication: indicationCode, missingUrl: url });
          }
        }

        // 3. Audit all dynamic workflow steps
        const workflow = deriveModuleWorkflow({
          caseId,
          indicationCode,
          activePath: `/cases/${caseId}`,
          isPhenotypeApproved: true,
          isMeasurementsComplete: true,
          isSlateReady: true,
          isDecisionSigned: false,
          isResearchOnly:
            bundle.mode === 'RESEARCH' || indicationCode === 'TINNITUS' || indicationCode === 'TBI',
        });

        for (const step of workflow.steps) {
          const resolvedStep = resolveUrlToPageFile(step.path);
          if (!resolvedStep) {
            failures.push({ caseId, indication: indicationCode, missingUrl: step.path });
          }

          if (step.subSteps) {
            for (const sub of step.subSteps) {
              const resolvedSub = resolveUrlToPageFile(sub.path);
              if (!resolvedSub) {
                failures.push({ caseId, indication: indicationCode, missingUrl: sub.path });
              }
            }
          }
        }
      }
    }

    expect(failures).toEqual([]);
  });

  it('verifies all 9 canonical indication modules resolve valid UI descriptors with zero unconfigured namespaces', () => {
    const allIndications = [
      'MDD',
      'PAIN',
      'STROKE_MOTOR',
      'STROKE_APHASIA',
      'OCD',
      'TINNITUS',
      'TBI',
      'SUD',
      'PTSD',
    ];

    for (const ind of allIndications) {
      const descriptor = getModuleUiDescriptor(ind);
      expect(descriptor).toBeDefined();
      expect(descriptor.indication_code).toBe(ind);
      expect(descriptor.context_sections.length).toBeGreaterThan(0);

      // Verify all context section routes exist for this indication
      for (const cs of descriptor.context_sections) {
        const url = `/cases/case-generic-01/${cs.pathSuffix}`;
        const resolved = resolveUrlToPageFile(url);
        expect(resolved, `Unresolved context section: ${url} for indication ${ind}`).not.toBeNull();
      }
    }
  });

  it('verifies all 9 canonical measurement modalities resolve without 404', () => {
    const modalities = [
      'structural-mri',
      'rs-fmri',
      'motor-mapping',
      'mep',
      'lesion-mask',
      'dwi',
      'task-fmri',
      'efield',
      'audiology',
    ];

    for (const mod of modalities) {
      const url = `/cases/case-v2-mdd-01/measurements/${mod}`;
      const resolved = resolveUrlToPageFile(url);
      expect(resolved).not.toBeNull();
      expect(fs.existsSync(resolved!)).toBe(true);
    }
  });

  it('verifies all 17 indication context routes resolve without 404', () => {
    const contextPaths = [
      'phenotype',
      'objective',
      'pain-context',
      'body-region',
      'impairment',
      'stage',
      'lesion',
      'aphasia-context',
      'slt-context',
      'ocd-context',
      'provocation-context',
      'tinnitus-context',
      'tbi-context',
      'substance-context',
      'cue-context',
      'ptsd-context',
      'trauma-context',
    ];

    for (const cp of contextPaths) {
      const url = `/cases/case-test-01/${cp}`;
      const resolved = resolveUrlToPageFile(url);
      expect(resolved, `Failed to resolve context sub-route: ${url}`).not.toBeNull();
      expect(fs.existsSync(resolved!)).toBe(true);
    }
  });

  it('verifies all canonical global routes specified in §190–§198 resolve without 404', () => {
    const globalRoutes = [
      '/',
      '/cases',
      '/cases/new',
      '/awaiting-review',
      '/reviews',
      '/decisions',
      '/evidence',
      '/evidence/claims',
      '/evidence/paths',
      '/evidence/target-families',
      '/evidence/sources',
      '/evidence/circuits',
      '/research',
      '/research/cases',
      '/research/modules',
      '/validation',
      '/validation/studies',
      '/validation/studies/VS-MDD-SILENT-001',
      '/validation/cases',
      '/validation/modules',
      '/validation/golden',
      '/internal',
      '/internal/verification',
      '/internal/golden-cases',
      '/internal/releases',
      '/internal/scientific-policy',
      '/internal/ci-status',
      '/admin',
      '/help',
      '/login',
    ];

    for (const gr of globalRoutes) {
      const resolved = resolveUrlToPageFile(gr);
      expect(resolved, `Failed to resolve canonical global route: ${gr}`).not.toBeNull();
      expect(fs.existsSync(resolved!)).toBe(true);
    }
  });

  it('verifies research notes route and multi-indication registry routes resolve without 404', () => {
    const testRoutes = [
      '/cases/case-v2-multi-11/indications',
      '/cases/case-v2-multi-11/indications/ci-51-mdd',
      '/cases/case-v2-multi-11/indications/ci-51-ptsd',
      '/cases/case-v2-multi-11/indications/ci-51-ptsd/context',
      '/cases/case-v2-multi-11/indications/ci-51-ptsd/targets',
      '/cases/case-v2-tinnitus-09/notes',
    ];

    for (const url of testRoutes) {
      const resolved = resolveUrlToPageFile(url);
      expect(resolved, `Failed to resolve route: ${url}`).not.toBeNull();
      expect(fs.existsSync(resolved!)).toBe(true);
    }
  });
});
