/**
 * Canonical Evidence Claims Manifest v2.0
 * Conforms to MAGNIOM-Evidence Knowledge Graph & Therapeutic Circuit Library v2.0 (§6, 24-70)
 * 36 versioned EvidenceClaims across 8 clinical indications
 */

import type { EvidenceClaimV2 } from '@magniom/domain';

export const CANONICAL_CLAIMS_V2: readonly EvidenceClaimV2[] = [
  // ----------------------------------------------------
  // MDD Claims (Preserved & Migrated Baseline)
  // ----------------------------------------------------
  {
    id: 'clm-mdd-001',
    code: 'EC-MDD-LDLPFC-EFFICACY-001',
    version: '2.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'High-frequency repetitive TMS to the left dorsolateral prefrontal cortex is clinically efficacious for treatment-resistant major depression.',
    direction: 'supports',
    indicationIds: ['ind-mdd-001'],
    outcomeDomainIds: ['dom-mdd-remission-001'],
    populationIds: ['pop-mdd-trd-001'],
    targetFamilyIds: ['TF-MDD-LDLPFC-001'],
    sourceContributions: [
      {
        sourceId: 'src-mdd-001',
        sourceFindingIds: [],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
      {
        sourceId: 'src-mdd-002',
        sourceFindingIds: ['fnd-mdd-001'],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Requires clinical confirmation of primary depression diagnosis.'],
    limitations: ['Moderate response rate; response latency typically 2 to 4 weeks.'],
    provenance: { createdBy: 'system_migration_adapter', createdAt: '2026-09-01T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-mdd-002',
    code: 'EC-MDD-LDLPFC-ITBS-001',
    version: '2.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'Intermittent theta burst stimulation (iTBS) to the left DLPFC is non-inferior to standard 10Hz rTMS for depression response.',
    direction: 'supports',
    indicationIds: ['ind-mdd-001'],
    outcomeDomainIds: ['dom-mdd-response-001'],
    populationIds: ['pop-mdd-trd-001'],
    targetFamilyIds: ['TF-MDD-LDLPFC-001'],
    sourceContributions: [
      {
        sourceId: 'src-mdd-003',
        sourceFindingIds: ['fnd-mdd-002'],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Adult TRD outpatients.'],
    limitations: ['Non-inferiority demonstrated; superior efficacy over 10Hz not established.'],
    provenance: { createdBy: 'system_migration_adapter', createdAt: '2026-09-01T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-mdd-003',
    code: 'EC-MDD-SGACC-ASSOCIATION-001',
    version: '2.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'circuit_validity',
    statement: 'Left DLPFC stimulation site functional anticorrelation with subgenual anterior cingulate cortex (sgACC) significantly associates with antidepressant outcome.',
    direction: 'supports',
    indicationIds: ['ind-mdd-001'],
    outcomeDomainIds: ['dom-mdd-response-001'],
    populationIds: ['pop-mdd-trd-001'],
    targetFamilyIds: ['TF-MDD-LDLPFC-001'],
    sourceContributions: [
      {
        sourceId: 'src-mdd-004',
        sourceFindingIds: ['fnd-mdd-003'],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Requires normative or high-reliability patient resting-state fMRI.'],
    limitations: ['Correlation with retrospective outcome; not a substitute for clinical diagnosis.'],
    provenance: { createdBy: 'system_migration_adapter', createdAt: '2026-09-01T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-mdd-004',
    code: 'EC-MDD-RDLPFC-001',
    version: '2.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'Low-frequency 1Hz stimulation to the right DLPFC is effective and well-tolerated as an alternative or add-on strategy for major depression.',
    direction: 'supports',
    indicationIds: ['ind-mdd-001'],
    outcomeDomainIds: ['dom-mdd-response-001'],
    populationIds: ['pop-mdd-trd-001'],
    targetFamilyIds: ['TF-MDD-RDLPFC-001'],
    sourceContributions: [
      {
        sourceId: 'src-cross-001',
        sourceFindingIds: [],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'contextual',
      },
    ],
    applicabilityConstraints: ['Considered when high-frequency left DLPFC is intolerable or contraindicated.'],
    limitations: ['Smaller overall randomized trial database compared to left DLPFC.'],
    provenance: { createdBy: 'system_migration_adapter', createdAt: '2026-09-01T00:00:00Z', softwareVersion: '2.0.0' },
  },

  // ----------------------------------------------------
  // OCD Claims
  // ----------------------------------------------------
  {
    id: 'clm-ocd-001',
    code: 'EC-OCD-MPFC-ACC-DTMS-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'Deep TMS engaging medial prefrontal and anterior cingulate cortices with personalized symptom provocation has established clinical treatment precedent for OCD.',
    direction: 'supports',
    indicationIds: ['ind-ocd-001'],
    outcomeDomainIds: ['dom-ocd-ybocs-001'],
    populationIds: ['pop-ocd-adult-001'],
    targetFamilyIds: ['TF-OCD-MPFC-ACC-FIELD-001'],
    sourceContributions: [
      {
        sourceId: 'src-ocd-001',
        sourceFindingIds: [],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
      {
        sourceId: 'src-ocd-002',
        sourceFindingIds: ['fnd-ocd-001'],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Requires cleared H7-coil deep-TMS system geometry and standardized provocation protocol.'],
    limitations: ['Does not validate arbitrary point-coordinate mPFC targeting; does not prove superiority over other targets.'],
    provenance: { createdBy: 'curator_ocd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-ocd-002',
    code: 'EC-OCD-MULTITARGET-META-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'comparative_efficacy',
    statement: 'Sham-controlled literature supports therapeutic effects across more than one OCD target family (DLPFC, SMA, mPFC/ACC) rather than identifying one universally superior coordinate.',
    direction: 'supports',
    indicationIds: ['ind-ocd-001'],
    outcomeDomainIds: ['dom-ocd-ybocs-001'],
    populationIds: ['pop-ocd-adult-001'],
    targetFamilyIds: ['TF-OCD-MPFC-ACC-FIELD-001', 'TF-OCD-PRESMA-SMA-001', 'TF-OCD-DLPFC-001'],
    sourceContributions: [
      {
        sourceId: 'src-ocd-003',
        sourceFindingIds: ['fnd-ocd-002'],
        relationship: 'supports',
        independence: 'partially_overlapping',
        relevance: 'direct',
      },
      {
        sourceId: 'src-ocd-006',
        sourceFindingIds: [],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Adult refractory OCD.'],
    limitations: ['Substantial trial heterogeneity and variable risk of bias across historical single-centre studies.'],
    provenance: { createdBy: 'curator_ocd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-ocd-003',
    code: 'EC-OCD-RCT-META-2025-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'Updated randomized evidence supports symptom reductions for DLPFC and mPFC/ACC approaches, but overall effect magnitude requires careful interpretation against minimal clinically important difference.',
    direction: 'context_dependent',
    indicationIds: ['ind-ocd-001'],
    outcomeDomainIds: ['dom-ocd-ybocs-001'],
    populationIds: ['pop-ocd-adult-001'],
    targetFamilyIds: ['TF-OCD-MPFC-ACC-FIELD-001', 'TF-OCD-DLPFC-001'],
    sourceContributions: [
      {
        sourceId: 'src-ocd-004',
        sourceFindingIds: ['fnd-ocd-003'],
        relationship: 'supports',
        independence: 'overlapping_dataset',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Adult refractory OCD.'],
    limitations: ['Mean symptom reduction was below the cited 4.0 minimal clinically important difference threshold.'],
    provenance: { createdBy: 'curator_ocd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-ocd-004',
    code: 'EC-OCD-LF-SURFACE-NULL-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'negative_evidence',
    statement: 'Low-frequency non-neuronavigated surface-coil rTMS, considered as a class, has not demonstrated statistically significant pooled benefit over sham in randomized evidence.',
    direction: 'does_not_support',
    indicationIds: ['ind-ocd-001'],
    outcomeDomainIds: ['dom-ocd-ybocs-001'],
    populationIds: ['pop-ocd-adult-001'],
    targetFamilyIds: ['TF-OCD-DLPFC-001', 'TF-OCD-PRESMA-SMA-001'],
    sourceContributions: [
      {
        sourceId: 'src-ocd-005',
        sourceFindingIds: ['fnd-ocd-004'],
        relationship: 'conflicts',
        independence: 'partially_overlapping',
        relevance: 'direct',
        curatorNote: 'Directly conflicts with overbroad claims that unnavigated surface-coil LF-rTMS is uniformly effective in OCD.',
      },
    ],
    applicabilityConstraints: ['Restricted to non-navigated figure-8 / surface-coil protocols.'],
    limitations: ['Does not generalize to deep-TMS or precisely navigated targets.'],
    provenance: { createdBy: 'curator_ocd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },

  // ----------------------------------------------------
  // Neuropathic Pain Claims
  // ----------------------------------------------------
  {
    id: 'clm-pain-001',
    code: 'EC-PAIN-HF-M1-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'High-frequency rTMS delivered to primary motor cortex (M1) contralateral to the painful body region has replicated analgesic efficacy in neuropathic pain.',
    direction: 'supports',
    indicationIds: ['ind-pain-001'],
    outcomeDomainIds: ['dom-pain-vas-001'],
    populationIds: ['pop-pain-chronic-001'],
    targetFamilyIds: ['TF-PAIN-M1-SOMATO-001'],
    sourceContributions: [
      {
        sourceId: 'src-cross-001',
        sourceFindingIds: [],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
      {
        sourceId: 'src-pain-004',
        sourceFindingIds: ['fnd-pain-001'],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Requires contralateral somatotopic M1 positioning matching painful anatomical distribution.'],
    limitations: ['External Level A recommendation does not automatically grant MAGNIOM clinical clearance.'],
    provenance: { createdBy: 'curator_pain_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-pain-002',
    code: 'EC-PAIN-RTMS-SHAM-META-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'Across heterogeneous neuropathic pain studies, active rTMS shows greater pain reduction than sham, with effect size modulated by stimulation frequency, target site and lesion location.',
    direction: 'supports',
    indicationIds: ['ind-pain-001'],
    outcomeDomainIds: ['dom-pain-vas-001'],
    populationIds: ['pop-pain-chronic-001'],
    targetFamilyIds: ['TF-PAIN-M1-SOMATO-001'],
    sourceContributions: [
      {
        sourceId: 'src-pain-001',
        sourceFindingIds: ['fnd-pain-002'],
        relationship: 'supports',
        independence: 'partially_overlapping',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Central and peripheral neuropathic pain.'],
    limitations: ['Effect size is substantially higher with navigation and high-frequency protocols.'],
    provenance: { createdBy: 'curator_pain_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-pain-003',
    code: 'EC-PAIN-M1-HETEROGENEITY-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'methodological_limitation',
    statement: 'M1 rTMS analgesia is heterogeneous, often transient, and evidence does not justify treating every neuropathic pain phenotype or body distribution as identical.',
    direction: 'context_dependent',
    indicationIds: ['ind-pain-001'],
    outcomeDomainIds: ['dom-pain-vas-001'],
    populationIds: ['pop-pain-chronic-001'],
    targetFamilyIds: ['TF-PAIN-M1-SOMATO-001'],
    sourceContributions: [
      {
        sourceId: 'src-pain-002',
        sourceFindingIds: ['fnd-pain-003'],
        relationship: 'limits_generalisation',
        independence: 'partially_overlapping',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Chronic neuropathic pain.'],
    limitations: ['Low certainty of evidence for several non-navigated and peripheral subgroups.'],
    provenance: { createdBy: 'curator_pain_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-pain-004',
    code: 'EC-PAIN-RMTS-CARE-POSITION-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'treatment_context',
    statement: 'Clinical practice guidelines recommend high-frequency motor cortex rTMS as a specialized third-line therapy within the broader neuropathic pain care algorithm.',
    direction: 'context_dependent',
    indicationIds: ['ind-pain-001'],
    outcomeDomainIds: ['dom-pain-vas-001'],
    populationIds: ['pop-pain-chronic-001'],
    targetFamilyIds: ['TF-PAIN-M1-SOMATO-001'],
    sourceContributions: [
      {
        sourceId: 'src-pain-003',
        sourceFindingIds: ['fnd-pain-004'],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'contextual',
      },
    ],
    applicabilityConstraints: ['Patients refractory to first- and second-line pharmacotherapies.'],
    limitations: ['Care algorithm position reflects clinical utility and access, distinct from experimental efficacy.'],
    provenance: { createdBy: 'curator_pain_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },

  // ----------------------------------------------------
  // Stroke Motor Recovery Claims
  // ----------------------------------------------------
  {
    id: 'clm-stroke-001',
    code: 'EC-STR-CM1-LF-POSTACUTE-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'Low-frequency rTMS to contralesional M1 has replicated real-versus-sham efficacy for hand motor recovery in post-acute stroke.',
    direction: 'supports',
    indicationIds: ['ind-stroke-001'],
    outcomeDomainIds: ['dom-stroke-fmau-001'],
    populationIds: ['pop-stroke-postacute-001'],
    diseaseStageDefinitionIds: ['stg-stroke-subacute-001'],
    targetFamilyIds: ['TF-STROKE-MOTOR-CM1-001'],
    sourceContributions: [
      {
        sourceId: 'src-cross-001',
        sourceFindingIds: [],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
      {
        sourceId: 'src-stroke-003',
        sourceFindingIds: ['fnd-stroke-001'],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Post-acute stage (subacute recovery window); mild-to-moderate paresis.'],
    limitations: ['Does not apply unconditionally to patients with severe structural corticospinal destruction.'],
    provenance: { createdBy: 'curator_stroke_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-stroke-002',
    code: 'EC-STR-IM1-HF-POSTACUTE-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'High-frequency ipsilesional M1 stimulation supports post-acute motor recovery, provided viable peri-infarct primary motor cortex remains intact.',
    direction: 'supports',
    indicationIds: ['ind-stroke-001'],
    outcomeDomainIds: ['dom-stroke-fmau-001'],
    populationIds: ['pop-stroke-postacute-001'],
    diseaseStageDefinitionIds: ['stg-stroke-subacute-001'],
    targetFamilyIds: ['TF-STROKE-MOTOR-IM1-001'],
    sourceContributions: [
      {
        sourceId: 'src-cross-001',
        sourceFindingIds: [],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
      {
        sourceId: 'src-stroke-001',
        sourceFindingIds: ['fnd-stroke-002'],
        relationship: 'supports',
        independence: 'partially_overlapping',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Target M1 cortex must not be destroyed by infarction.'],
    limitations: ['Guidelines grade evidence strength lower than contralesional low-frequency stimulation.'],
    provenance: { createdBy: 'curator_stroke_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-stroke-003',
    code: 'EC-STR-MOTOR-RCTMETA-2025-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'In randomized trials restricted to low risk of bias, rTMS improves upper-extremity motor outcomes, with significantly greater gains in acute/subacute patients.',
    direction: 'supports',
    indicationIds: ['ind-stroke-001'],
    outcomeDomainIds: ['dom-stroke-fmau-001'],
    populationIds: ['pop-stroke-postacute-001'],
    diseaseStageDefinitionIds: ['stg-stroke-subacute-001'],
    targetFamilyIds: ['TF-STROKE-MOTOR-CM1-001', 'TF-STROKE-MOTOR-IM1-001'],
    sourceContributions: [
      {
        sourceId: 'src-stroke-001',
        sourceFindingIds: ['fnd-stroke-002'],
        relationship: 'supports',
        independence: 'partially_overlapping',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Acute and subacute stroke stages.'],
    limitations: ['Chronic stroke demonstrates smaller, more heterogeneous functional improvements.'],
    provenance: { createdBy: 'curator_stroke_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-stroke-004',
    code: 'EC-STR-IHI-NOT-UNIVERSAL-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'mechanistic',
    statement: 'The model that contralesional motor cortex is uniformly maladaptive does not hold in severely affected patients with extensive ipsilesional pathway destruction.',
    direction: 'context_dependent',
    indicationIds: ['ind-stroke-001'],
    outcomeDomainIds: ['dom-stroke-fmau-001'],
    populationIds: ['pop-stroke-postacute-001'],
    targetFamilyIds: ['TF-STROKE-MOTOR-CM1-001'],
    sourceContributions: [
      {
        sourceId: 'src-stroke-002',
        sourceFindingIds: ['fnd-stroke-003'],
        relationship: 'limits_generalisation',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Severe hemiparesis with profound corticospinal tract lesion load.'],
    limitations: ['Inhibiting contralesional cortex in this subgroup may worsen functional capacity.'],
    provenance: { createdBy: 'curator_stroke_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },

  // ----------------------------------------------------
  // Post-Stroke Aphasia Claims
  // ----------------------------------------------------
  {
    id: 'clm-psa-001',
    code: 'EC-PSA-RIFG-LF-CHRONIC-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'Low-frequency stimulation of the right inferior frontal gyrus has replicated evidence for chronic post-stroke non-fluent aphasia.',
    direction: 'supports',
    indicationIds: ['ind-aphasia-001'],
    outcomeDomainIds: ['dom-psa-naming-001'],
    populationIds: ['pop-aphasia-chronic-nonfluent-001'],
    diseaseStageDefinitionIds: ['stg-stroke-chronic-001'],
    targetFamilyIds: ['TF-PSA-RIFG-001'],
    sourceContributions: [
      {
        sourceId: 'src-cross-001',
        sourceFindingIds: [],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
      {
        sourceId: 'src-psa-004',
        sourceFindingIds: ['fnd-psa-001'],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Chronic stage, non-fluent (Broca-type) aphasia.'],
    limitations: ['Does not generalize to fluent/Wernicke aphasia or acute unselected strokes.'],
    provenance: { createdBy: 'curator_aphasia_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-psa-002',
    code: 'EC-PSA-RTMS-SLT-META-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'treatment_context',
    statement: 'rTMS combined with speech-language therapy (SLT) produces improvements across multiple language domains compared with sham plus SLT or SLT alone.',
    direction: 'supports',
    indicationIds: ['ind-aphasia-001'],
    outcomeDomainIds: ['dom-psa-naming-001', 'dom-psa-comp-001', 'dom-psa-rep-001'],
    populationIds: ['pop-aphasia-chronic-nonfluent-001'],
    targetFamilyIds: ['TF-PSA-RIFG-001'],
    treatmentContextRequirementIds: ['tc-slt-001'],
    sourceContributions: [
      {
        sourceId: 'src-psa-001',
        sourceFindingIds: ['fnd-psa-002'],
        relationship: 'supports',
        independence: 'partially_overlapping',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Must be delivered in close temporal pairing with structured speech therapy.'],
    limitations: ['Evidence does not support rTMS delivered in isolation without behavioral speech rehabilitation.'],
    provenance: { createdBy: 'curator_aphasia_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-psa-003',
    code: 'EC-PSA-OVERALL-RCTMETA-2026-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'Pooled meta-analysis indicates significant rTMS efficacy for language recovery, with stimulation site, chronicity, and individual targeting acting as critical moderators.',
    direction: 'supports',
    indicationIds: ['ind-aphasia-001'],
    outcomeDomainIds: ['dom-psa-naming-001'],
    populationIds: ['pop-aphasia-chronic-nonfluent-001'],
    targetFamilyIds: ['TF-PSA-RIFG-001'],
    sourceContributions: [
      {
        sourceId: 'src-psa-002',
        sourceFindingIds: [],
        relationship: 'supports',
        independence: 'partially_overlapping',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Target and disease-stage semantics must remain granular.'],
    limitations: ['Heterogeneous language outcome batteries across included RCTs.'],
    provenance: { createdBy: 'curator_aphasia_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-psa-004',
    code: 'EC-PSA-CONTEXT-HETEROGENEITY-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'methodological_limitation',
    statement: 'Network meta-analysis reveals that different rTMS+SLT strategies rank inconsistently across immediate vs long-term language domains, precluding a single universal best aphasia protocol.',
    direction: 'context_dependent',
    indicationIds: ['ind-aphasia-001'],
    outcomeDomainIds: ['dom-psa-naming-001'],
    populationIds: ['pop-aphasia-chronic-nonfluent-001'],
    targetFamilyIds: ['TF-PSA-RIFG-001'],
    sourceContributions: [
      {
        sourceId: 'src-psa-003',
        sourceFindingIds: ['fnd-psa-003'],
        relationship: 'limits_generalisation',
        independence: 'partially_overlapping',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Chronic aphasia.'],
    limitations: ['Certain dual-hemisphere combinations carry very low evidence certainty due to imprecision.'],
    provenance: { createdBy: 'curator_aphasia_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },

  // ----------------------------------------------------
  // Traumatic Brain Injury (TBI) Claims
  // ----------------------------------------------------
  {
    id: 'clm-tbi-001',
    code: 'EC-TBI-META2025-COG-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'Meta-analysis of seven randomized trials reported a significant pooled improvement in cognitive test performance after rTMS post-TBI.',
    direction: 'supports',
    indicationIds: ['ind-tbi-001'],
    outcomeDomainIds: ['dom-tbi-cog-001'],
    populationIds: ['pop-tbi-adult-001'],
    targetFamilyIds: [], // Intentionally empty pending primary-study extraction (§50, 87)
    sourceContributions: [
      {
        sourceId: 'src-tbi-001',
        sourceFindingIds: ['fnd-tbi-001'],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
      {
        sourceId: 'src-tbi-004',
        sourceFindingIds: ['fnd-tbi-003'],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Target specificity is unresolved; target family assignment requires primary-study extraction.'],
    limitations: ['Small total participant count across trials; diverse cognitive batteries.'],
    provenance: { createdBy: 'curator_tbi_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-tbi-002',
    code: 'EC-TBI-META2025-PAIN-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'Pooled randomized trials in traumatic brain injury reported significant reductions in post-traumatic headache and central pain scores.',
    direction: 'supports',
    indicationIds: ['ind-tbi-001'],
    outcomeDomainIds: ['dom-tbi-pain-001'],
    populationIds: ['pop-tbi-adult-001'],
    targetFamilyIds: [], // Intentionally empty pending extraction
    sourceContributions: [
      {
        sourceId: 'src-tbi-001',
        sourceFindingIds: ['fnd-tbi-001'],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Post-traumatic headache and pain phenotypes.'],
    limitations: ['Clinical efficacy signal does not equate to a validated MAGNIOM target family.'],
    provenance: { createdBy: 'curator_tbi_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-tbi-003',
    code: 'EC-TBI-META2025-DEP-NULL-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'negative_evidence',
    statement: 'The 2025 pooled meta-analysis found no statistically significant benefit of rTMS over sham for post-TBI depressive symptoms.',
    direction: 'does_not_support',
    indicationIds: ['ind-tbi-001'],
    outcomeDomainIds: ['dom-tbi-dep-001'],
    populationIds: ['pop-tbi-adult-001'],
    targetFamilyIds: [],
    sourceContributions: [
      {
        sourceId: 'src-tbi-001',
        sourceFindingIds: ['fnd-tbi-001'],
        relationship: 'conflicts',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Post-TBI depression outcome domain.'],
    limitations: ['Conflicts with earlier smaller studies claiming depression benefit in TBI.'],
    provenance: { createdBy: 'curator_tbi_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-tbi-004',
    code: 'EC-TBI-EARLIER-DEP-POSITIVE-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'Prior systematic synthesis found short-term reduction in post-TBI depression scores with prefrontal rTMS, though durability was unverified.',
    direction: 'mixed',
    indicationIds: ['ind-tbi-001'],
    outcomeDomainIds: ['dom-tbi-dep-001'],
    populationIds: ['pop-tbi-adult-001'],
    targetFamilyIds: [],
    sourceContributions: [
      {
        sourceId: 'src-tbi-003',
        sourceFindingIds: [],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Adult post-TBI depression.'],
    limitations: ['Long-term durability uncertain; conflicting contemporary syntheses.'],
    provenance: { createdBy: 'curator_tbi_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-tbi-005',
    code: 'EC-TBI-TSA2026-CONFLICT-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'negative_evidence',
    statement: 'Trial sequential analysis in 2026 found that pooled cognitive and mood improvements post-TBI fail to meet required statistical information thresholds, concluding evidence is inconclusive.',
    direction: 'does_not_support',
    indicationIds: ['ind-tbi-001'],
    outcomeDomainIds: ['dom-tbi-cog-001', 'dom-tbi-dep-001'],
    populationIds: ['pop-tbi-adult-001'],
    targetFamilyIds: [],
    sourceContributions: [
      {
        sourceId: 'src-tbi-002',
        sourceFindingIds: ['fnd-tbi-002'],
        relationship: 'conflicts',
        independence: 'partially_overlapping',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Cognitive and depressive outcomes in TBI.'],
    limitations: ['Directly conflicts with 2025 positive meta-analytic estimates.'],
    provenance: { createdBy: 'curator_tbi_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },

  // ----------------------------------------------------
  // PTSD Claims
  // ----------------------------------------------------
  {
    id: 'clm-ptsd-001',
    code: 'EC-PTSD-RDLPFC-HF-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'High-frequency right-DLPFC rTMS has replicated sham-controlled efficacy for reducing core symptoms in civilian post-traumatic stress disorder.',
    direction: 'supports',
    indicationIds: ['ind-ptsd-001'],
    outcomeDomainIds: ['dom-ptsd-caps-001'],
    populationIds: ['pop-ptsd-civilian-001'],
    targetFamilyIds: ['TF-PTSD-RDLPFC-001'],
    sourceContributions: [
      {
        sourceId: 'src-cross-001',
        sourceFindingIds: [],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
      {
        sourceId: 'src-ptsd-004',
        sourceFindingIds: ['fnd-ptsd-001'],
        relationship: 'supports',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Civilian trauma populations; high-frequency right DLPFC protocols.'],
    limitations: ['Must carry population boundary; does not extrapolate to combat-related trauma.'],
    provenance: { createdBy: 'curator_ptsd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-ptsd-002',
    code: 'EC-PTSD-META-2024-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'Meta-analysis of randomized sham-controlled PTSD trials reported substantial overall symptom reductions and post-treatment durability, but sample sizes remain moderate.',
    direction: 'supports',
    indicationIds: ['ind-ptsd-001'],
    outcomeDomainIds: ['dom-ptsd-caps-001'],
    populationIds: ['pop-ptsd-general-001'],
    targetFamilyIds: ['TF-PTSD-RDLPFC-001'],
    sourceContributions: [
      {
        sourceId: 'src-ptsd-001',
        sourceFindingIds: [],
        relationship: 'supports',
        independence: 'partially_overlapping',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['General PTSD populations.'],
    limitations: ['Does not differentiate veteran combat-related non-response.'],
    provenance: { createdBy: 'curator_ptsd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-ptsd-003',
    code: 'EC-PTSD-TARGET-COMPARE-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'comparative_efficacy',
    statement: 'Network meta-analysis identified high-frequency right DLPFC as significantly outperforming sham and trending superior to low-frequency right DLPFC for PTSD symptom resolution.',
    direction: 'supports',
    indicationIds: ['ind-ptsd-001'],
    outcomeDomainIds: ['dom-ptsd-caps-001'],
    populationIds: ['pop-ptsd-general-001'],
    targetFamilyIds: ['TF-PTSD-RDLPFC-001', 'TF-PTSD-LDLPFC-001'],
    sourceContributions: [
      {
        sourceId: 'src-ptsd-002',
        sourceFindingIds: ['fnd-ptsd-002'],
        relationship: 'supports',
        independence: 'partially_overlapping',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Target Family and stimulation frequency must remain distinct.'],
    limitations: ['Indirect comparisons present in network models.'],
    provenance: { createdBy: 'curator_ptsd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-ptsd-004',
    code: 'EC-PTSD-COMBAT-CONFLICT-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'negative_evidence',
    statement: 'Meta-analysis focused on combat-related veteran PTSD trials revealed a non-significant pooled active-versus-sham difference driven by high sham response rates.',
    direction: 'does_not_support',
    indicationIds: ['ind-ptsd-001'],
    outcomeDomainIds: ['dom-ptsd-caps-001'],
    populationIds: ['pop-ptsd-combat-001'],
    targetFamilyIds: ['TF-PTSD-RDLPFC-001'],
    sourceContributions: [
      {
        sourceId: 'src-ptsd-003',
        sourceFindingIds: ['fnd-ptsd-003'],
        relationship: 'conflicts',
        independence: 'independent',
        relevance: 'direct',
        curatorNote: 'Population-specific conflict: prohibits automatic extrapolation of civilian PTSD efficacy to combat PTSD.',
      },
    ],
    applicabilityConstraints: ['Combat-exposed veterans.'],
    limitations: ['Large within-group changes in both active and sham groups.'],
    provenance: { createdBy: 'curator_ptsd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },

  // ----------------------------------------------------
  // Tinnitus Claims
  // ----------------------------------------------------
  {
    id: 'clm-tin-001',
    code: 'EC-TIN-ROUTINE-TMS-GUIDELINE-NEG-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'negative_evidence',
    statement: 'The AAO-HNS clinical practice guideline recommends against clinicians recommending routine transcranial magnetic stimulation for persistent, bothersome tinnitus.',
    direction: 'does_not_support',
    indicationIds: ['ind-tinnitus-001'],
    outcomeDomainIds: ['dom-tin-thi-001'],
    populationIds: ['pop-tinnitus-chronic-001'],
    targetFamilyIds: ['TF-TIN-TEMPORAL-001', 'TF-TIN-TPJ-001'],
    sourceContributions: [
      {
        sourceId: 'src-tin-001',
        sourceFindingIds: ['fnd-tin-001'],
        relationship: 'conflicts',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Routine clinical care for persistent tinnitus.'],
    limitations: ['Guideline recommendation reflects risk-benefit and overall evidence quality.'],
    provenance: { createdBy: 'curator_tinnitus_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-tin-002',
    code: 'EC-TIN-LF-META2020-NULL-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'negative_evidence',
    statement: 'Systematic review and meta-analysis of ten randomized trials found no significant benefit of low-frequency rTMS over sham for tinnitus handicap or loudness.',
    direction: 'does_not_support',
    indicationIds: ['ind-tinnitus-001'],
    outcomeDomainIds: ['dom-tin-thi-001', 'dom-tin-loud-001'],
    populationIds: ['pop-tinnitus-chronic-001'],
    targetFamilyIds: ['TF-TIN-TEMPORAL-001'],
    sourceContributions: [
      {
        sourceId: 'src-tin-002',
        sourceFindingIds: ['fnd-tin-003'],
        relationship: 'conflicts',
        independence: 'independent',
        relevance: 'direct',
      },
      {
        sourceId: 'src-tin-006',
        sourceFindingIds: ['fnd-tin-002'],
        relationship: 'conflicts',
        independence: 'independent',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Low-frequency temporal rTMS.'],
    limitations: ['Null pooled result across examining follow-up windows.'],
    provenance: { createdBy: 'curator_tinnitus_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-tin-003',
    code: 'EC-TIN-META2025-MIXED-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'Meta-analysis of 16 trials found modest short-term reduction in THI distress, but no significant benefit on perceived loudness and attenuation to non-significance by 6 months.',
    direction: 'mixed',
    indicationIds: ['ind-tinnitus-001'],
    outcomeDomainIds: ['dom-tin-thi-001'],
    populationIds: ['pop-tinnitus-chronic-001'],
    targetFamilyIds: ['TF-TIN-TEMPORAL-001', 'TF-TIN-TPJ-001'],
    sourceContributions: [
      {
        sourceId: 'src-tin-003',
        sourceFindingIds: ['fnd-tin-004'],
        relationship: 'partially_supports',
        independence: 'partially_overlapping',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Chronic subjective tinnitus.'],
    limitations: ['Durability beyond acute treatment window is unconfirmed.'],
    provenance: { createdBy: 'curator_tinnitus_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-tin-004',
    code: 'EC-TIN-META2026A-NULL-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'negative_evidence',
    statement: 'A comprehensive 2026 systematic review found the pooled rTMS effect on chronic subjective tinnitus to be non-significant in robust double-blind randomized trials.',
    direction: 'does_not_support',
    indicationIds: ['ind-tinnitus-001'],
    outcomeDomainIds: ['dom-tin-thi-001'],
    populationIds: ['pop-tinnitus-chronic-001'],
    targetFamilyIds: ['TF-TIN-TEMPORAL-001', 'TF-TIN-TPJ-001'],
    sourceContributions: [
      {
        sourceId: 'src-tin-004',
        sourceFindingIds: ['fnd-tin-005'],
        relationship: 'conflicts',
        independence: 'partially_overlapping',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Double-blind sham-controlled trials.'],
    limitations: ['Directly conflicts with smaller positive open-label cohorts.'],
    provenance: { createdBy: 'curator_tinnitus_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'clm-tin-005',
    code: 'EC-TIN-META2026B-SHORTTERM-001',
    version: '1.0.0',
    lifecycleStatus: 'approved_scientific_claim',
    claimType: 'clinical_efficacy',
    statement: 'A contemporary 2026 meta-analysis reported modest immediate THI benefit with rTMS but inconsistent secondary outcomes and high heterogeneity across protocol variants.',
    direction: 'mixed',
    indicationIds: ['ind-tinnitus-001'],
    outcomeDomainIds: ['dom-tin-thi-001'],
    populationIds: ['pop-tinnitus-chronic-001'],
    targetFamilyIds: ['TF-TIN-TEMPORAL-001', 'TF-TIN-FRONTOTEMP-001'],
    sourceContributions: [
      {
        sourceId: 'src-tin-005',
        sourceFindingIds: [],
        relationship: 'partially_supports',
        independence: 'partially_overlapping',
        relevance: 'direct',
      },
    ],
    applicabilityConstraints: ['Immediate post-treatment assessment only.'],
    limitations: ['Substantial inter-study heterogeneity; conflicting syntheses.'],
    provenance: { createdBy: 'curator_tinnitus_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
];
