/**
 * Canonical Evidence Governance Classifications Manifest v2.0
 * Conforms to MAGNIOM-Evidence Knowledge Graph & Therapeutic Circuit Library v2.0 (§7, 8, 106, 107)
 * Strictly enforces Anti-Premature Tier Promotion Rule
 */

import type { EvidenceGovernanceClassification } from '@magniom/domain';

export const CANONICAL_GOVERNANCE_CLASSIFICATIONS: readonly EvidenceGovernanceClassification[] = [
  // ----------------------------------------------------
  // MDD Migrated Governance Classifications (§106, 107)
  // Preserved as assigned with migrated_v1_governance basis
  // ----------------------------------------------------
  {
    id: 'gov-mdd-001',
    evidenceClaimId: 'clm-mdd-001',
    claimVersion: '2.0.0',
    classificationStatus: 'assigned',
    magniomEvidenceTier: 'A',
    permittedRoles: {
      standalonePrimary: true,
      standaloneAdditional: true,
      supportingContext: true,
      refinementOfParentClaims: true,
      researchCandidateGeneration: true,
    },
    reviewerIds: ['rev-gov-scientific-chair', 'rev-gov-clinical-chair'],
    rationale: 'Historical v1 Tier 1 MDD efficacy claim migrated into v2 Tier A governance status.',
    classificationBasis: 'migrated_v1_governance',
    supportingSynthesisId: 'syn-mdd-001',
    assignedAt: '2026-09-01T00:00:00Z',
    provenance: { createdBy: 'system_migration_adapter', createdAt: '2026-09-01T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-mdd-002',
    evidenceClaimId: 'clm-mdd-002',
    claimVersion: '2.0.0',
    classificationStatus: 'assigned',
    magniomEvidenceTier: 'A',
    permittedRoles: {
      standalonePrimary: true,
      standaloneAdditional: true,
      supportingContext: true,
      refinementOfParentClaims: true,
      researchCandidateGeneration: true,
    },
    reviewerIds: ['rev-gov-scientific-chair', 'rev-gov-clinical-chair'],
    rationale: 'Historical v1 Tier 1 MDD iTBS non-inferiority claim migrated into v2 Tier A.',
    classificationBasis: 'migrated_v1_governance',
    supportingSynthesisId: 'syn-mdd-002',
    assignedAt: '2026-09-01T00:00:00Z',
    provenance: { createdBy: 'system_migration_adapter', createdAt: '2026-09-01T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-mdd-003',
    evidenceClaimId: 'clm-mdd-003',
    claimVersion: '2.0.0',
    classificationStatus: 'assigned',
    magniomEvidenceTier: 'B',
    permittedRoles: {
      standalonePrimary: false,
      standaloneAdditional: true,
      supportingContext: true,
      refinementOfParentClaims: true,
      researchCandidateGeneration: true,
    },
    reviewerIds: ['rev-gov-scientific-chair', 'rev-gov-clinical-chair'],
    rationale: 'Historical v1 Tier 2 MDD sgACC refinement claim migrated into v2 Tier B.',
    classificationBasis: 'migrated_v1_governance',
    supportingSynthesisId: 'syn-mdd-003',
    assignedAt: '2026-09-01T00:00:00Z',
    provenance: { createdBy: 'system_migration_adapter', createdAt: '2026-09-01T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-mdd-004',
    evidenceClaimId: 'clm-mdd-004',
    claimVersion: '2.0.0',
    classificationStatus: 'assigned',
    magniomEvidenceTier: 'B',
    permittedRoles: {
      standalonePrimary: true,
      standaloneAdditional: true,
      supportingContext: true,
      refinementOfParentClaims: false,
      researchCandidateGeneration: true,
    },
    reviewerIds: ['rev-gov-scientific-chair', 'rev-gov-clinical-chair'],
    rationale: 'Historical v1 Tier 2 MDD right DLPFC 1Hz alternative claim migrated into v2 Tier B.',
    classificationBasis: 'migrated_v1_governance',
    supportingSynthesisId: 'syn-mdd-004',
    assignedAt: '2026-09-01T00:00:00Z',
    provenance: { createdBy: 'system_migration_adapter', createdAt: '2026-09-01T00:00:00Z', softwareVersion: '2.0.0' },
  },

  // ----------------------------------------------------
  // OCD Staging Governance (UNASSIGNED) (§8, 26-29)
  // ----------------------------------------------------
  {
    id: 'gov-ocd-001',
    evidenceClaimId: 'clm-ocd-001',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-ocd-lead'],
    rationale: 'Seeded in evidence staging; clinical tier assignment deferred pending prospective module validation.',
    supportingSynthesisId: 'syn-ocd-001',
    provenance: { createdBy: 'curator_ocd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-ocd-002',
    evidenceClaimId: 'clm-ocd-002',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-ocd-lead'],
    rationale: 'Multi-target comparative synthesis; tier unassigned until clinical governance review.',
    supportingSynthesisId: 'syn-ocd-002',
    provenance: { createdBy: 'curator_ocd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-ocd-003',
    evidenceClaimId: 'clm-ocd-003',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-ocd-lead'],
    rationale: 'Clinical importance threshold under evaluation; tier unassigned.',
    supportingSynthesisId: 'syn-ocd-003',
    provenance: { createdBy: 'curator_ocd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-ocd-004',
    evidenceClaimId: 'clm-ocd-004',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-ocd-lead'],
    rationale: 'Null low-frequency synthesis; negative evidence retained without clinical tier promotion.',
    supportingSynthesisId: 'syn-ocd-004',
    provenance: { createdBy: 'curator_ocd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },

  // ----------------------------------------------------
  // Neuropathic Pain Staging Governance (UNASSIGNED) (§32-35)
  // ----------------------------------------------------
  {
    id: 'gov-pain-001',
    evidenceClaimId: 'clm-pain-001',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-pain-lead'],
    rationale: 'European Level A finding recognized; MAGNIOM Tier remains unassigned pending Gate B approval.',
    supportingSynthesisId: 'syn-pain-001',
    provenance: { createdBy: 'curator_pain_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-pain-002',
    evidenceClaimId: 'clm-pain-002',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-pain-lead'],
    rationale: 'M1 pooled efficacy synthesis; tier unassigned.',
    supportingSynthesisId: 'syn-pain-002',
    provenance: { createdBy: 'curator_pain_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-pain-003',
    evidenceClaimId: 'clm-pain-003',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-pain-lead'],
    rationale: 'Methodological heterogeneity limitation; tier unassigned.',
    supportingSynthesisId: 'syn-pain-003',
    provenance: { createdBy: 'curator_pain_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-pain-004',
    evidenceClaimId: 'clm-pain-004',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-pain-lead'],
    rationale: 'Care algorithm context; tier unassigned.',
    supportingSynthesisId: 'syn-pain-004',
    provenance: { createdBy: 'curator_pain_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },

  // ----------------------------------------------------
  // Stroke Motor Governance (UNASSIGNED) (§38-41)
  // ----------------------------------------------------
  {
    id: 'gov-stroke-001',
    evidenceClaimId: 'clm-stroke-001',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-stroke-lead'],
    rationale: 'Post-acute contralesional M1 low-frequency evidence seeded in staging; tier unassigned.',
    supportingSynthesisId: 'syn-stroke-001',
    provenance: { createdBy: 'curator_stroke_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-stroke-002',
    evidenceClaimId: 'clm-stroke-002',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-stroke-lead'],
    rationale: 'Ipsilesional M1 high-frequency evidence seeded in staging; tier unassigned.',
    supportingSynthesisId: 'syn-stroke-002',
    provenance: { createdBy: 'curator_stroke_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-stroke-003',
    evidenceClaimId: 'clm-stroke-003',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-stroke-lead'],
    rationale: 'Stage-dependent meta-analytic evidence; tier unassigned.',
    supportingSynthesisId: 'syn-stroke-003',
    provenance: { createdBy: 'curator_stroke_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-stroke-004',
    evidenceClaimId: 'clm-stroke-004',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-stroke-lead'],
    rationale: 'Mechanistic reserve limitation; tier unassigned.',
    supportingSynthesisId: 'syn-stroke-004',
    provenance: { createdBy: 'curator_stroke_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },

  // ----------------------------------------------------
  // Post-Stroke Aphasia Governance (UNASSIGNED) (§45-48)
  // ----------------------------------------------------
  {
    id: 'gov-psa-001',
    evidenceClaimId: 'clm-psa-001',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-aphasia-lead'],
    rationale: 'Right IFG 1Hz chronic non-fluent aphasia protocol; tier unassigned.',
    supportingSynthesisId: 'syn-psa-001',
    provenance: { createdBy: 'curator_aphasia_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-psa-002',
    evidenceClaimId: 'clm-psa-002',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-aphasia-lead'],
    rationale: 'Mandatory concurrent SLT treatment-context claim; tier unassigned.',
    supportingSynthesisId: 'syn-psa-002',
    provenance: { createdBy: 'curator_aphasia_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-psa-003',
    evidenceClaimId: 'clm-psa-003',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-aphasia-lead'],
    rationale: 'Language recovery moderator synthesis; tier unassigned.',
    supportingSynthesisId: 'syn-psa-003',
    provenance: { createdBy: 'curator_aphasia_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-psa-004',
    evidenceClaimId: 'clm-psa-004',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-aphasia-lead'],
    rationale: 'Protocol heterogeneity limitation; tier unassigned.',
    supportingSynthesisId: 'syn-psa-004',
    provenance: { createdBy: 'curator_aphasia_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },

  // ----------------------------------------------------
  // TBI Governance (UNASSIGNED) (§51-55)
  // ----------------------------------------------------
  {
    id: 'gov-tbi-001',
    evidenceClaimId: 'clm-tbi-001',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-tbi-lead'],
    rationale: 'Cognitive signal in TBI; target family unresolved, tier unassigned.',
    supportingSynthesisId: 'syn-tbi-001',
    provenance: { createdBy: 'curator_tbi_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-tbi-002',
    evidenceClaimId: 'clm-tbi-002',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-tbi-lead'],
    rationale: 'Pain signal in TBI; tier unassigned.',
    supportingSynthesisId: 'syn-tbi-002',
    provenance: { createdBy: 'curator_tbi_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-tbi-003',
    evidenceClaimId: 'clm-tbi-003',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-tbi-lead'],
    rationale: 'Null depression finding; tier unassigned.',
    supportingSynthesisId: 'syn-tbi-003',
    provenance: { createdBy: 'curator_tbi_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-tbi-004',
    evidenceClaimId: 'clm-tbi-004',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-tbi-lead'],
    rationale: 'Conflicting depression claim; tier unassigned.',
    supportingSynthesisId: 'syn-tbi-004',
    provenance: { createdBy: 'curator_tbi_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-tbi-005',
    evidenceClaimId: 'clm-tbi-005',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-tbi-lead'],
    rationale: 'Trial sequential analysis showing insufficient evidence; tier unassigned.',
    supportingSynthesisId: 'syn-tbi-005',
    provenance: { createdBy: 'curator_tbi_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },

  // ----------------------------------------------------
  // PTSD Governance (UNASSIGNED) (§59-62)
  // ----------------------------------------------------
  {
    id: 'gov-ptsd-001',
    evidenceClaimId: 'clm-ptsd-001',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-ptsd-lead'],
    rationale: 'Civilian right DLPFC efficacy finding; tier unassigned.',
    supportingSynthesisId: 'syn-ptsd-001',
    provenance: { createdBy: 'curator_ptsd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-ptsd-002',
    evidenceClaimId: 'clm-ptsd-002',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-ptsd-lead'],
    rationale: 'General PTSD randomized meta-analysis; tier unassigned.',
    supportingSynthesisId: 'syn-ptsd-002',
    provenance: { createdBy: 'curator_ptsd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-ptsd-003',
    evidenceClaimId: 'clm-ptsd-003',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-ptsd-lead'],
    rationale: 'Comparative target network meta-analysis; tier unassigned.',
    supportingSynthesisId: 'syn-ptsd-003',
    provenance: { createdBy: 'curator_ptsd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-ptsd-004',
    evidenceClaimId: 'clm-ptsd-004',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-ptsd-lead'],
    rationale: 'Combat-related veteran population conflict; tier unassigned.',
    supportingSynthesisId: 'syn-ptsd-004',
    provenance: { createdBy: 'curator_ptsd_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },

  // ----------------------------------------------------
  // Tinnitus Governance (UNASSIGNED / RESEARCH) (§66-70)
  // ----------------------------------------------------
  {
    id: 'gov-tin-001',
    evidenceClaimId: 'clm-tin-001',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-tinnitus-lead'],
    rationale: 'AAO-HNS guideline against routine rTMS; negative evidence prominently stored, tier unassigned.',
    supportingSynthesisId: 'syn-tin-001',
    provenance: { createdBy: 'curator_tinnitus_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-tin-002',
    evidenceClaimId: 'clm-tin-002',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-tinnitus-lead'],
    rationale: 'Null low-frequency rTMS randomized evidence; tier unassigned.',
    supportingSynthesisId: 'syn-tin-002',
    provenance: { createdBy: 'curator_tinnitus_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-tin-003',
    evidenceClaimId: 'clm-tin-003',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-tinnitus-lead'],
    rationale: 'Mixed short-term benefit with non-significant 6-month durability; tier unassigned.',
    supportingSynthesisId: 'syn-tin-003',
    provenance: { createdBy: 'curator_tinnitus_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-tin-004',
    evidenceClaimId: 'clm-tin-004',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-tinnitus-lead'],
    rationale: '2026 non-significant pooled rTMS synthesis; tier unassigned.',
    supportingSynthesisId: 'syn-tin-004',
    provenance: { createdBy: 'curator_tinnitus_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
  {
    id: 'gov-tin-005',
    evidenceClaimId: 'clm-tin-005',
    claimVersion: '1.0.0',
    classificationStatus: 'unassigned',
    reviewerIds: ['rev-gov-tinnitus-lead'],
    rationale: '2026 contradictory modest-benefit synthesis; tier unassigned.',
    supportingSynthesisId: 'syn-tin-005',
    provenance: { createdBy: 'curator_tinnitus_panel', createdAt: '2026-09-02T00:00:00Z', softwareVersion: '2.0.0' },
  },
];
