/**
 * Canonical PICO Evidence Questions v2.0
 * Conforms to MAGNIOM-Evidence Knowledge Graph & Therapeutic Circuit Library v2.0 (§75)
 */

import type { EvidenceQuestion } from '@magniom/domain';

export const CANONICAL_EVIDENCE_QUESTIONS: readonly EvidenceQuestion[] = [
  {
    id: 'q-mdd-001',
    indicationId: 'ind-mdd-001',
    population: { description: 'Adults with treatment-resistant major depressive disorder', ageMin: 18, ageMax: 70 },
    clinicalObjectiveId: 'obj-mdd-core-001',
    targetFamilyId: 'tf-mdd-001',
    targetingStrategyId: 'strat-sgc-fconn',
    comparator: { type: 'sham', device: 'active_sham_shielded' },
    outcomeDomains: ['out-mdd-depression-severity', 'out-mdd-remission'],
    question: 'Does personalized rs-fMRI SGC-anticorrelated DLPFC rTMS produce superior remission rates compared to standard anatomical landmark targeting in TRD?',
    status: 'answered_provisionally',
  },
  {
    id: 'q-ocd-001',
    indicationId: 'ind-ocd-001',
    population: { description: 'Adults with severe treatment-refractory OCD with medication resistance', ybocsMin: 20 },
    clinicalObjectiveId: 'obj-ocd-core-001',
    targetFamilyId: 'TF-OCD-MPFC-ACC-FIELD-001',
    targetingStrategyId: 'strat-ocd-dtms-h7',
    treatmentContextId: 'ctx-ocd-provocation-001',
    comparator: { type: 'sham', device: 'sham_h7_coil' },
    outcomeDomains: ['out-ocd-ybocs-total', 'out-ocd-response-rate'],
    question: 'Does high-frequency bilateral deep TMS over mPFC/ACC combined with individualized symptom provocation achieve durable Y-BOCS reduction over sham?',
    status: 'answered_provisionally',
  },
  {
    id: 'q-pain-001',
    indicationId: 'ind-pain-001',
    population: { description: 'Adults with refractory central or peripheral neuropathic pain', painDurationMonthsMin: 6 },
    clinicalObjectiveId: 'obj-pain-reduction-001',
    targetFamilyId: 'TF-PAIN-M1-SOMATO-001',
    targetingStrategyId: 'strat-pain-m1-somato',
    comparator: { type: 'sham', description: 'tilted coil or placebo sham' },
    outcomeDomains: ['out-pain-vas-reduction', 'out-pain-quality-of-life'],
    question: 'Does high-frequency (10–20Hz) rTMS to contralateral somatotopic M1 achieve clinically significant pain reduction in refractory neuropathic pain?',
    status: 'answered_provisionally',
  },
  {
    id: 'q-stroke-001',
    indicationId: 'ind-stroke-001',
    population: { description: 'Post-stroke patients in subacute phase (2 weeks to 6 months) with upper-extremity paresis' },
    clinicalObjectiveId: 'obj-stroke-ue-motor-001',
    targetFamilyId: 'TF-STROKE-MOTOR-CM1-001',
    targetingStrategyId: 'strat-stroke-cm1-lf',
    comparator: { type: 'sham_plus_rehab' },
    outcomeDomains: ['out-stroke-fugl-meyer', 'out-stroke-action-research-arm'],
    question: 'Does low-frequency (1Hz) inhibitory rTMS over contralesional M1 combined with physical therapy accelerate upper-limb motor recovery in subacute ischemic stroke?',
    status: 'answered_provisionally',
  },
  {
    id: 'q-aphasia-001',
    indicationId: 'ind-aphasia-001',
    population: { description: 'Chronic post-stroke non-fluent aphasia (>6 months post-onset) with impaired object naming' },
    clinicalObjectiveId: 'obj-aphasia-naming-001',
    targetFamilyId: 'TF-PSA-RIFG-001',
    targetingStrategyId: 'strat-aphasia-rifg-1hz',
    treatmentContextId: 'tc-slt-001',
    comparator: { type: 'sham_plus_slt' },
    outcomeDomains: ['out-aphasia-wab-aq', 'out-aphasia-boston-naming'],
    question: 'Does low-frequency rTMS over right IFG pars triangularis paired with concurrent speech-language therapy significantly improve language recovery in chronic non-fluent aphasia?',
    status: 'answered_provisionally',
  },
  {
    id: 'q-tbi-001',
    indicationId: 'ind-tbi-001',
    population: { description: 'Adults with chronic post-TBI executive dysfunction and persistent post-concussive symptoms' },
    clinicalObjectiveId: 'obj-tbi-cog-001',
    targetFamilyId: 'TF-TBI-DLPFC-001',
    targetingStrategyId: 'strat-tbi-exploratory-f3',
    comparator: { type: 'sham' },
    outcomeDomains: ['out-tbi-executive-score', 'out-tbi-working-memory'],
    question: 'Does high-frequency rTMS to left DLPFC demonstrate a reliable and replicated benefit over sham for cognitive recovery after traumatic brain injury?',
    status: 'under_review',
  },
  {
    id: 'q-ptsd-001',
    indicationId: 'ind-ptsd-001',
    population: { description: 'Military veterans with combat-related treatment-resistant PTSD' },
    clinicalObjectiveId: 'obj-ptsd-core-001',
    targetFamilyId: 'TF-PTSD-RDLPFC-001',
    targetingStrategyId: 'strat-ptsd-rdlpfc-hf',
    comparator: { type: 'active_sham_e_field_matched' },
    outcomeDomains: ['out-ptsd-caps-5', 'out-ptsd-pcl-5'],
    question: 'Does high-frequency right DLPFC rTMS produce superior symptom improvement compared with active sham in combat-related PTSD?',
    status: 'under_review',
  },
  {
    id: 'q-tinnitus-001',
    indicationId: 'ind-tinnitus-001',
    population: { description: 'Adults with persistent, bothersome subjective non-pulsatile chronic tinnitus (>6 months)' },
    clinicalObjectiveId: 'obj-tin-distress-001',
    targetFamilyId: 'TF-TIN-TEMPORAL-AUDITORY-001',
    targetingStrategyId: 'strat-tin-a1-1hz',
    comparator: { type: 'sham' },
    outcomeDomains: ['out-tin-thi-score', 'out-tin-tq-score'],
    question: 'Does low-frequency repetitive TMS over auditory cortex produce clinically meaningful, durable improvements in tinnitus-related handicap over sham?',
    status: 'under_review',
  },
];
