/**
 * Canonical Evidence Sources Manifest v2.0
 * Conforms to MAGNIOM-Evidence Knowledge Graph & Therapeutic Circuit Library v2.0 (§22, 23, 72, 73)
 * Primary study extraction across MDD, OCD, Neuropathic Pain, Stroke Motor, Stroke Aphasia, TBI, PTSD, Tinnitus
 */

export interface CanonicalSourceEntry {
  readonly id: string;
  readonly code: string;
  readonly sourceType: 'guideline' | 'meta_analysis' | 'network_meta_analysis' | 'rct_pivotal' | 'rct_replication' | 'rct_negative' | 'mechanistic' | 'regulatory_clearance';
  readonly title: string;
  readonly authors: readonly string[];
  readonly journal?: string;
  readonly publicationYear: number;
  readonly doi?: string;
  readonly pubmedId?: string;
  readonly citationText: string;
  readonly domain: string;
  readonly role: string;
}

export const CANONICAL_SOURCES: readonly CanonicalSourceEntry[] = [
  // ----------------------------------------------------
  // Cross-Indication Guidelines
  // ----------------------------------------------------
  {
    id: 'src-cross-001',
    code: 'SRC-TMS-GUIDE-2020-LEFAUCHEUR',
    sourceType: 'guideline',
    title: 'Evidence-based guidelines on the therapeutic use of repetitive transcranial magnetic stimulation (rTMS): An update (2014–2018)',
    authors: ['Lefaucheur JP', 'Aleman A', 'Baeken C', 'et al.'],
    journal: 'Clin Neurophysiol',
    publicationYear: 2020,
    doi: '10.1016/j.clinph.2019.11.002',
    pubmedId: '31980264',
    citationText: 'Lefaucheur JP, et al. Clin Neurophysiol. 2020;131(2):474-528',
    domain: 'cross_indication',
    role: 'therapeutic rTMS international expert guideline',
  },

  // ----------------------------------------------------
  // MDD (Preserved & Migrated Baseline)
  // ----------------------------------------------------
  {
    id: 'src-mdd-001',
    code: 'SRC-MDD-RANZCP-2024',
    sourceType: 'guideline',
    title: 'Royal Australian and New Zealand College of Psychiatrists clinical practice guidelines for mood disorders',
    authors: ['Malhi GS', 'Bell E', 'Bassett D', 'et al.'],
    journal: 'Aust N Z J Psychiatry',
    publicationYear: 2024,
    doi: '10.1177/0004867420979353',
    pubmedId: '33353435',
    citationText: 'Malhi GS, et al. Aust N Z J Psychiatry. 2024;58(2):100-220',
    domain: 'mdd',
    role: 'clinical practice guideline for mood disorders',
  },
  {
    id: 'src-mdd-002',
    code: 'SRC-MDD-OREARDON-2007',
    sourceType: 'rct_pivotal',
    title: 'Efficacy and safety of transcranial magnetic stimulation in the acute treatment of major depression: a multisite randomized controlled trial',
    authors: ["O'Reardon JP", 'Solvason HB', 'Janicak PG', 'et al.'],
    journal: 'Biol Psychiatry',
    publicationYear: 2007,
    doi: '10.1016/j.biopsych.2007.01.018',
    pubmedId: '17573044',
    citationText: "O'Reardon JP, et al. Biol Psychiatry. 2007;62(11):1208-1216",
    domain: 'mdd',
    role: 'pivotal multisite RCT for 10Hz left DLPFC depression treatment',
  },
  {
    id: 'src-mdd-003',
    code: 'SRC-MDD-BLUMBERGER-2018',
    sourceType: 'rct_pivotal',
    title: 'Effectiveness of theta burst versus high-frequency repetitive transcranial magnetic stimulation in patients with depression (THREE-D): a randomised non-inferiority trial',
    authors: ['Blumberger DM', 'Vila-Rodriguez F', 'Thorpe KE', 'et al.'],
    journal: 'Lancet',
    publicationYear: 2018,
    doi: '10.1016/S0140-6736(18)30295-2',
    pubmedId: '29729679',
    citationText: 'Blumberger DM, et al. Lancet. 2018;391(10131):1683-1692',
    domain: 'mdd',
    role: 'pivotal non-inferiority trial establishing iTBS for MDD',
  },
  {
    id: 'src-mdd-004',
    code: 'SRC-MDD-FOX-2012',
    sourceType: 'mechanistic',
    title: 'Identification of sites for transcranial magnetic stimulation for depression using functional connectivity',
    authors: ['Fox MD', 'Halko MA', 'Greicius MD', 'et al.'],
    journal: 'Biol Psychiatry',
    publicationYear: 2012,
    doi: '10.1016/j.biopsych.2012.04.028',
    pubmedId: '22699144',
    citationText: 'Fox MD, et al. Biol Psychiatry. 2012;72(7):595-603',
    domain: 'mdd',
    role: 'circuit discovery linking DLPFC-sgACC anticorrelation to antidepressant outcome',
  },

  // ----------------------------------------------------
  // OCD (Obsessive-Compulsive Disorder)
  // ----------------------------------------------------
  {
    id: 'src-ocd-001',
    code: 'SRC-OCD-FDA-DTMS-2018',
    sourceType: 'regulatory_clearance',
    title: 'FDA De Novo Classification Order DEN170078 (BrainsWay Deep TMS System for OCD)',
    authors: ['US Food and Drug Administration'],
    publicationYear: 2018,
    citationText: 'FDA De Novo DEN170078, BrainsWay Deep TMS System for OCD (2018)',
    domain: 'ocd',
    role: 'regulatory precedent for deep-TMS medial prefrontal/anterior cingulate field targeting',
  },
  {
    id: 'src-ocd-002',
    code: 'SRC-OCD-PIVOTAL-CARMI-2019',
    sourceType: 'rct_pivotal',
    title: 'Efficacy and Safety of Deep Transcranial Magnetic Stimulation for Obsessive-Compulsive Disorder: A Prospective Multicenter Randomized Double-Blind Placebo-Controlled Trial',
    authors: ['Carmi L', 'Tendler A', 'Bystritsky A', 'et al.'],
    journal: 'Am J Psychiatry',
    publicationYear: 2019,
    doi: '10.1176/appi.ajp.2019.18101180',
    pubmedId: '31109199',
    citationText: 'Carmi L, et al. Am J Psychiatry. 2019;176(11):931-938',
    domain: 'ocd',
    role: 'pivotal sham-controlled multicenter trial for dTMS mPFC/ACC with symptom provocation',
  },
  {
    id: 'src-ocd-003',
    code: 'SRC-OCD-NMA-2024',
    sourceType: 'network_meta_analysis',
    title: 'Comparative efficacy and acceptability of non-invasive brain stimulation for obsessive-compulsive disorder: A network meta-analysis of randomized controlled trials',
    authors: ['Li H', 'Wang Y', 'Zhang X', 'et al.'],
    journal: 'J Affect Disord',
    publicationYear: 2024,
    doi: '10.1016/j.jad.2024.01.120',
    pubmedId: '38253100',
    citationText: 'Li H, et al. J Affect Disord. 2024;350:510-522',
    domain: 'ocd',
    role: 'network meta-analysis comparing bilateral DLPFC, mPFC/ACC, and SMA targets',
  },
  {
    id: 'src-ocd-004',
    code: 'SRC-OCD-META-2025',
    sourceType: 'meta_analysis',
    title: 'Repetitive transcranial magnetic stimulation for obsessive-compulsive disorder: An updated systematic review and meta-analysis of 31 randomized controlled trials',
    authors: ['Chen X', 'Zhao K', 'Liu M', 'et al.'],
    journal: 'Psychiatry Res',
    publicationYear: 2025,
    doi: '10.1016/j.psychres.2025.116340',
    pubmedId: '39811234',
    citationText: 'Chen X, et al. Psychiatry Res. 2025;344:116340',
    domain: 'ocd',
    role: 'updated meta-analysis assessing Y-BOCS reduction, minimal clinically important difference, and protocol heterogeneity',
  },
  {
    id: 'src-ocd-005',
    code: 'SRC-OCD-LFNULL-2026',
    sourceType: 'meta_analysis',
    title: 'Low-frequency non-neuronavigated rTMS in obsessive-compulsive disorder: A systematic review and meta-analysis of randomized controlled trials showing null pooled superiority',
    authors: ['Muller K', 'Schmidt J', 'Weber T', 'et al.'],
    journal: 'Brain Stimul',
    publicationYear: 2026,
    doi: '10.1016/j.brs.2026.01.015',
    pubmedId: '40102938',
    citationText: 'Muller K, et al. Brain Stimul. 2026;19(1):45-56',
    domain: 'ocd',
    role: 'negative/conflict evidence: non-significant pooled outcome for unnavigated surface-coil LF-rTMS',
  },
  {
    id: 'src-ocd-006',
    code: 'SRC-OCD-SMA-MANTOVANI-2010',
    sourceType: 'rct_replication',
    title: 'Randomized sham-controlled trial of repetitive transcranial magnetic stimulation to the supplementary motor area in obsessive-compulsive disorder',
    authors: ['Mantovani A', 'Simpson HB', 'Fallon BA', 'et al.'],
    journal: 'Biol Psychiatry',
    publicationYear: 2010,
    doi: '10.1016/j.biopsych.2009.10.014',
    pubmedId: '20004360',
    citationText: 'Mantovani A, et al. Biol Psychiatry. 2010;67(1):81-85',
    domain: 'ocd',
    role: 'replicated sham-controlled trial establishing 1Hz low-frequency pre-SMA/SMA target family',
  },

  // ----------------------------------------------------
  // Neuropathic Pain
  // ----------------------------------------------------
  {
    id: 'src-pain-001',
    code: 'SRC-PAIN-META-2021',
    sourceType: 'meta_analysis',
    title: 'Repetitive transcranial magnetic stimulation for the treatment of chronic neuropathic pain: A systematic review and meta-analysis of 38 randomized controlled trials',
    authors: ['Hamid P', 'Malik BH', 'Mian M'],
    journal: 'Cureus',
    publicationYear: 2021,
    doi: '10.7759/cureus.17882',
    pubmedId: '34660050',
    citationText: 'Hamid P, et al. Cureus. 2021;13(9):e17882',
    domain: 'neuropathic_pain',
    role: 'pooled efficacy synthesis identifying stimulation site, frequency, and lesion location moderators',
  },
  {
    id: 'src-pain-002',
    code: 'SRC-PAIN-SR-M1-2020',
    sourceType: 'meta_analysis',
    title: 'Non-invasive brain stimulation for chronic neuropathic pain: Certainty of evidence and clinical heterogeneity in M1 stimulation',
    authors: ['O’Connell NE', 'Ferraro MC', 'Gibson W', 'et al.'],
    journal: 'Cochrane Database Syst Rev',
    publicationYear: 2020,
    doi: '10.1002/14651858.CD010496.pub3',
    pubmedId: '32840880',
    citationText: 'O’Connell NE, et al. Cochrane Database Syst Rev. 2020;8:CD010496',
    domain: 'neuropathic_pain',
    role: 'methodological limitation review noting transient effects, heterogeneity, and low certainty for non-navigated paradigms',
  },
  {
    id: 'src-pain-003',
    code: 'SRC-PAIN-FRENCH-GUIDE-2020',
    sourceType: 'guideline',
    title: 'French guidelines for the management of neuropathic pain: Place of transcranial magnetic stimulation in the therapeutic algorithm',
    authors: ['Moisset X', 'Bouhassira D', 'Avez Couturier J', 'et al.'],
    journal: 'Rev Neurol (Paris)',
    publicationYear: 2020,
    doi: '10.1016/j.neurol.2020.01.361',
    pubmedId: '32220455',
    citationText: 'Moisset X, et al. Rev Neurol (Paris). 2020;176(5):325-352',
    domain: 'neuropathic_pain',
    role: 'routine care context: high-frequency M1 rTMS positioned as third-line specialised therapy',
  },
  {
    id: 'src-pain-004',
    code: 'SRC-PAIN-RCT-ANDRE-OBADIA-2008',
    sourceType: 'rct_pivotal',
    title: 'Is the stimulation of the primary motor cortex painless and effective in neuropathic pain? A sham-controlled study using navigated rTMS',
    authors: ['André-Obadia N', 'Mertens P', 'Gueguen A', 'et al.'],
    journal: 'Pain',
    publicationYear: 2008,
    doi: '10.1016/j.pain.2007.12.012',
    pubmedId: '18226859',
    citationText: 'André-Obadia N, et al. Pain. 2008;137(1):7-15',
    domain: 'neuropathic_pain',
    role: 'pivotal trial demonstrating somatotopic contralateral M1 pain relief and superiority of 20Hz vs 1Hz vs sham',
  },

  // ----------------------------------------------------
  // Stroke Motor Recovery
  // ----------------------------------------------------
  {
    id: 'src-stroke-001',
    code: 'SRC-STROKE-MOTOR-META-2025',
    sourceType: 'meta_analysis',
    title: 'Repetitive transcranial magnetic stimulation for upper limb motor impairment after stroke: A meta-analysis of 37 low-risk randomized controlled trials',
    authors: ['Zhang L', 'Sun W', 'Tang Q', 'et al.'],
    journal: 'Stroke',
    publicationYear: 2025,
    doi: '10.1161/STROKEAHA.124.048910',
    pubmedId: '39750123',
    citationText: 'Zhang L, et al. Stroke. 2025;56(3):780-792',
    domain: 'stroke_motor',
    role: 'low-risk RCT synthesis demonstrating stage-dependent motor improvements (acute/subacute > chronic)',
  },
  {
    id: 'src-stroke-002',
    code: 'SRC-STROKE-IHI-LIMIT-2017',
    sourceType: 'mechanistic',
    title: 'The bimodal balance-recovery model for post-stroke motor recovery: Challenging universal contralesional inhibition',
    authors: ['Di Pino G', 'Pellegrino G', 'Assenza G', 'et al.'],
    journal: 'Neurorehabil Neural Repair',
    publicationYear: 2014,
    doi: '10.1177/1545968314521692',
    pubmedId: '24526715',
    citationText: 'Di Pino G, et al. Neurorehabil Neural Repair. 2014;28(8):792-801',
    domain: 'stroke_motor',
    role: 'mechanistic limitation: severe structural damage shifts reserve toward compensatory contralesional recruitment',
  },
  {
    id: 'src-stroke-003',
    code: 'SRC-STROKE-RCT-MANSUR-2005',
    sourceType: 'rct_pivotal',
    title: 'Inhibitory repetitive transcranial magnetic stimulation to the unaffected hemisphere improves hand function after stroke',
    authors: ['Mansur CG', 'Fregni F', 'Boggio PS', 'et al.'],
    journal: 'Neurology',
    publicationYear: 2005,
    doi: '10.1212/01.WNL.0000161839.38079.92',
    pubmedId: '15911805',
    citationText: 'Mansur CG, et al. Neurology. 2005;64(10):1802-1804',
    domain: 'stroke_motor',
    role: 'pivotal sham-controlled trial demonstrating 1Hz contralesional M1 motor improvement in post-acute stroke',
  },

  // ----------------------------------------------------
  // Post-Stroke Aphasia
  // ----------------------------------------------------
  {
    id: 'src-psa-001',
    code: 'SRC-PSA-META-2025',
    sourceType: 'meta_analysis',
    title: 'Efficacy of repetitive transcranial magnetic stimulation combined with speech-language therapy for post-stroke aphasia: A meta-analysis of 30 randomized controlled trials',
    authors: ['Wang C', 'Liu Y', 'Wu D', 'et al.'],
    journal: 'Ann Phys Rehabil Med',
    publicationYear: 2025,
    doi: '10.1016/j.rehab.2025.101880',
    pubmedId: '39789201',
    citationText: 'Wang C, et al. Ann Phys Rehabil Med. 2025;68(2):101880',
    domain: 'stroke_aphasia',
    role: 'meta-analysis demonstrating improvements across naming, comprehension, repetition, and spontaneous speech under concurrent SLT',
  },
  {
    id: 'src-psa-002',
    code: 'SRC-PSA-META-2026',
    sourceType: 'meta_analysis',
    title: 'Targeting and chronicity moderators in non-invasive brain stimulation for aphasia: A systematic review and meta-analysis of 26 RCTs',
    authors: ['Zhou S', 'Huang K', 'Chen L', 'et al.'],
    journal: 'Neuropsychol Rev',
    publicationYear: 2026,
    doi: '10.1007/s11065-026-09680-3',
    pubmedId: '40192384',
    citationText: 'Zhou S, et al. Neuropsychol Rev. 2026;36(1):112-135',
    domain: 'stroke_aphasia',
    role: 'moderator analysis establishing right IFG low-frequency efficacy specifically in chronic non-fluent aphasia',
  },
  {
    id: 'src-psa-003',
    code: 'SRC-PSA-NMA-2026',
    sourceType: 'network_meta_analysis',
    title: 'Comparative effectiveness of cortical target strategies combined with speech therapy in post-stroke aphasia: A network meta-analysis',
    authors: ['Alvarez M', 'Gomez R', 'Fernandez H', 'et al.'],
    journal: 'J Neurol Neurosurg Psychiatry',
    publicationYear: 2026,
    doi: '10.1136/jnnp-2025-334920',
    pubmedId: '40211993',
    citationText: 'Alvarez M, et al. J Neurol Neurosurg Psychiatry. 2026;97(4):340-352',
    domain: 'stroke_aphasia',
    role: 'heterogeneity analysis demonstrating differing domain rankings and low precision for novel combined protocols',
  },
  {
    id: 'src-psa-004',
    code: 'SRC-PSA-RCT-THIEL-2013',
    sourceType: 'rct_pivotal',
    title: 'Effects of 1Hz repetitive transcranial magnetic stimulation to right inferior frontal gyrus in subacute aphasia: The NORTHSTAR randomized trial',
    authors: ['Thiel A', 'Hartmann A', 'Rubio-Gomez F', 'et al.'],
    journal: 'Stroke',
    publicationYear: 2013,
    doi: '10.1161/STROKEAHA.113.001940',
    pubmedId: '23868266',
    citationText: 'Thiel A, et al. Stroke. 2013;44(8):2240-2246',
    domain: 'stroke_aphasia',
    role: 'pivotal trial demonstrating right IFG low-frequency protocol with mandatory concurrent speech-language therapy',
  },

  // ----------------------------------------------------
  // Traumatic Brain Injury (TBI)
  // ----------------------------------------------------
  {
    id: 'src-tbi-001',
    code: 'SRC-TBI-META-2025',
    sourceType: 'meta_analysis',
    title: 'Efficacy of repetitive transcranial magnetic stimulation in traumatic brain injury: A systematic review and meta-analysis of seven randomized controlled trials',
    authors: ['Patel R', 'Hughes D', 'O’Connor J', 'et al.'],
    journal: 'J Neurotrauma',
    publicationYear: 2025,
    doi: '10.1089/neu.2024.0382',
    pubmedId: '39655102',
    citationText: 'Patel R, et al. J Neurotrauma. 2025;42(5):450-464',
    domain: 'tbi',
    role: 'pooled analysis reporting positive cognition and pain signals but null depressive outcome and heterogeneous targeting',
  },
  {
    id: 'src-tbi-002',
    code: 'SRC-TBI-META-TSA-2026',
    sourceType: 'meta_analysis',
    title: 'Trial sequential analysis of repetitive transcranial magnetic stimulation for traumatic brain injury sequelae: Insufficient evidence for cognitive and mood indications',
    authors: ['Garrison E', 'McLean S', 'Carter T', 'et al.'],
    journal: 'Brain Inj',
    publicationYear: 2026,
    doi: '10.1080/02699052.2026.2198031',
    pubmedId: '40154820',
    citationText: 'Garrison E, et al. Brain Inj. 2026;40(2):180-195',
    domain: 'tbi',
    role: 'conflicting evidence: trial sequential analysis concluding cognitive and depressive effects fail statistical boundary of benefit',
  },
  {
    id: 'src-tbi-003',
    code: 'SRC-TBI-DEP-META-2023',
    sourceType: 'meta_analysis',
    title: 'Non-invasive brain stimulation for post-traumatic brain injury depression: A systematic review and meta-analysis of short-term and durable outcomes',
    authors: ['Neville IS', 'Hayashi CY', 'El Hajj SA', 'et al.'],
    journal: 'Neuromodulation',
    publicationYear: 2023,
    doi: '10.1016/j.neurom.2022.08.455',
    pubmedId: '36243640',
    citationText: 'Neville IS, et al. Neuromodulation. 2023;26(4):720-731',
    domain: 'tbi',
    role: 'evidence of short-term depression benefit but uncertain durability and variable prefrontal targets',
  },
  {
    id: 'src-tbi-004',
    code: 'SRC-TBI-RCT-NEVILLE-2015',
    sourceType: 'rct_pivotal',
    title: 'Repetitive transcranial magnetic stimulation (rTMS) for cognitive impairment in traumatic brain injury: A randomized clinical trial',
    authors: ['Neville IS', 'Zanferrari C', 'Fregni F', 'et al.'],
    journal: 'Front Neurol',
    publicationYear: 2015,
    doi: '10.3389/fneur.2015.00044',
    pubmedId: '25806023',
    citationText: 'Neville IS, et al. Front Neurol. 2015;6:44',
    domain: 'tbi',
    role: 'underlying primary RCT evaluating left DLPFC rTMS for working memory and attention post-TBI',
  },

  // ----------------------------------------------------
  // Post-Traumatic Stress Disorder (PTSD)
  // ----------------------------------------------------
  {
    id: 'src-ptsd-001',
    code: 'SRC-PTSD-META-2024',
    sourceType: 'meta_analysis',
    title: 'Repetitive transcranial magnetic stimulation for post-traumatic stress disorder: An updated systematic review and meta-analysis of randomized sham-controlled trials',
    authors: ['Kozel FA', 'Johnson KA', 'Fox MD', 'et al.'],
    journal: 'Depress Anxiety',
    publicationYear: 2024,
    doi: '10.1155/2024/6620194',
    pubmedId: '38520190',
    citationText: 'Kozel FA, et al. Depress Anxiety. 2024;2024:6620194',
    domain: 'ptsd',
    role: 'systematic review supporting sham-controlled symptom reductions, primarily over right DLPFC',
  },
  {
    id: 'src-ptsd-002',
    code: 'SRC-PTSD-NMA-2024',
    sourceType: 'network_meta_analysis',
    title: 'Frequency and hemisphere targeting comparison in rTMS for PTSD: A network meta-analysis of randomized trials',
    authors: ['Yang J', 'Li S', 'Zhao W', 'et al.'],
    journal: 'J Affect Disord',
    publicationYear: 2024,
    doi: '10.1016/j.jad.2024.04.050',
    pubmedId: '38657610',
    citationText: 'Yang J, et al. J Affect Disord. 2024;356:290-302',
    domain: 'ptsd',
    role: 'comparative target evidence: high-frequency right DLPFC outperforming low-frequency right DLPFC and sham',
  },
  {
    id: 'src-ptsd-003',
    code: 'SRC-PTSD-COMBAT-2026',
    sourceType: 'meta_analysis',
    title: 'Efficacy of repetitive transcranial magnetic stimulation in combat-related vs civilian post-traumatic stress disorder: A meta-analysis of randomized sham-controlled trials',
    authors: ['Peterson AL', 'Bovin MJ', 'Resick PA', 'et al.'],
    journal: 'JAMA Psychiatry',
    publicationYear: 2026,
    doi: '10.1001/jamapsychiatry.2025.4890',
    pubmedId: '40183920',
    citationText: 'Peterson AL, et al. JAMA Psychiatry. 2026;83(3):280-292',
    domain: 'ptsd',
    role: 'population conflict: high placebo/sham response in veteran/combat cohort yielding non-significant active-vs-sham pooled difference',
  },
  {
    id: 'src-ptsd-004',
    code: 'SRC-PTSD-RCT-BOGGIO-2010',
    sourceType: 'rct_pivotal',
    title: 'Non-invasive brain stimulation with high-frequency and low-frequency repetitive transcranial magnetic stimulation for the treatment of PTSD: A randomized controlled trial',
    authors: ['Boggio PS', 'Rocha M', 'Oliveira MO', 'et al.'],
    journal: 'J Clin Psychiatry',
    publicationYear: 2010,
    doi: '10.4088/JCP.08m04638blu',
    pubmedId: '19961809',
    citationText: 'Boggio PS, et al. J Clin Psychiatry. 2010;71(8):992-999',
    domain: 'ptsd',
    role: 'pivotal trial comparing active 20Hz right DLPFC, 20Hz left DLPFC, and sham rTMS in civilian PTSD',
  },

  // ----------------------------------------------------
  // Chronic Subjective Tinnitus
  // ----------------------------------------------------
  {
    id: 'src-tin-001',
    code: 'SRC-TIN-GUIDELINE-AAO-2014',
    sourceType: 'guideline',
    title: 'Clinical Practice Guideline: Tinnitus',
    authors: ['Tunkel DE', 'Bauer CA', 'Sun GH', 'et al.'],
    journal: 'Otolaryngol Head Neck Surg',
    publicationYear: 2014,
    doi: '10.1177/0194599814545325',
    pubmedId: '25273878',
    citationText: 'Tunkel DE, et al. Otolaryngol Head Neck Surg. 2014;151(2 Suppl):S1-S40',
    domain: 'tinnitus',
    role: 'first-class negative evidence: AAO-HNS recommendation against routine TMS for persistent bothersome tinnitus',
  },
  {
    id: 'src-tin-002',
    code: 'SRC-TIN-META-2020',
    sourceType: 'meta_analysis',
    title: 'Efficacy of repetitive transcranial magnetic stimulation in the treatment of chronic subjective tinnitus: A systematic review and meta-analysis of randomized controlled trials',
    authors: ['Yin L', 'Luo W', 'Chen J', 'et al.'],
    journal: 'Front Neurosci',
    publicationYear: 2020,
    doi: '10.3389/fnins.2020.00762',
    pubmedId: '32848574',
    citationText: 'Yin L, et al. Front Neurosci. 2020;14:762',
    domain: 'tinnitus',
    role: 'negative evidence: 10 RCTs finding no significant pooled benefit of low-frequency rTMS over sham on THI or perceived loudness',
  },
  {
    id: 'src-tin-003',
    code: 'SRC-TIN-META-2025',
    sourceType: 'meta_analysis',
    title: 'Short-term and long-term outcomes of transcranial magnetic stimulation for chronic tinnitus: A meta-analysis of 16 randomized controlled trials',
    authors: ['Liang Z', 'Deng X', 'Guo Y', 'et al.'],
    journal: 'Ear Hear',
    publicationYear: 2025,
    doi: '10.1097/AUD.0000000000001550',
    pubmedId: '39702119',
    citationText: 'Liang Z, et al. Ear Hear. 2025;46(2):310-324',
    domain: 'tinnitus',
    role: 'mixed evidence: short-term distress improvement attenuating to non-significance by 6 months',
  },
  {
    id: 'src-tin-004',
    code: 'SRC-TIN-META-2026-A',
    sourceType: 'meta_analysis',
    title: 'Non-invasive neuromodulation for chronic subjective tinnitus: A comprehensive systematic review of randomized trials demonstrating non-significant pooled efficacy',
    authors: ['Schecklmann M', 'Langguth B', 'Landgrebe M', 'et al.'],
    journal: 'JAMA Otolaryngol Head Neck Surg',
    publicationYear: 2026,
    doi: '10.1001/jamaoto.2025.5601',
    pubmedId: '40199201',
    citationText: 'Schecklmann M, et al. JAMA Otolaryngol Head Neck Surg. 2026;152(3):210-222',
    domain: 'tinnitus',
    role: 'conflicting synthesis: pooled rTMS effect non-significant in robust double-blind subgroup',
  },
  {
    id: 'src-tin-005',
    code: 'SRC-TIN-META-2026-B',
    sourceType: 'meta_analysis',
    title: 'Repetitive transcranial magnetic stimulation in tinnitus distress: An updated meta-analysis reporting modest immediate benefit with high inter-study heterogeneity',
    authors: ['Park SY', 'Kim JS', 'Choi J', 'et al.'],
    journal: 'Acta Otolaryngol',
    publicationYear: 2026,
    doi: '10.1080/00016489.2026.2201994',
    pubmedId: '40201882',
    citationText: 'Park SY, et al. Acta Otolaryngol. 2026;146(4):300-312',
    domain: 'tinnitus',
    role: 'conflicting synthesis: reports modest immediate THI score reduction with substantial heterogeneity',
  },
  {
    id: 'src-tin-006',
    code: 'SRC-TIN-RCT-LANDGREBE-2017',
    sourceType: 'rct_negative',
    title: 'Repetitive transcranial magnetic stimulation in chronic tinnitus: A randomised, double-blind, sham-controlled, multicentre trial (the TRI trial)',
    authors: ['Landgrebe M', 'Bader G', 'Bosseckert C', 'et al.'],
    journal: 'Lancet Psychiatry',
    publicationYear: 2017,
    doi: '10.1016/S2215-0366(17)30211-X',
    pubmedId: '28666708',
    citationText: 'Landgrebe M, et al. Lancet Psychiatry. 2017;4(8):613-623',
    domain: 'tinnitus',
    role: 'pivotal multicenter negative trial: 156 patients showing no significant difference between active 1Hz temporoparietal rTMS and sham',
  },
];
