/**
 * Canonical Claim Evidence Syntheses Manifest v2.0
 * Conforms to MAGNIOM-Evidence Knowledge Graph & Therapeutic Circuit Library v2.0 (§12, 502-568)
 * Dimensional multi-attribute evidence synthesis for versioned claims
 */

import type { ClaimEvidenceSynthesis } from '@magniom/domain';

export const CANONICAL_SYNTHESES: readonly ClaimEvidenceSynthesis[] = [
  // ----------------------------------------------------
  // MDD Syntheses
  // ----------------------------------------------------
  {
    id: 'syn-mdd-001',
    evidenceClaimId: 'clm-mdd-001',
    directness: 'strong',
    replication: 'multiple_independent',
    studyDesignStrength: 'strong',
    sampleSupport: 'strong',
    consistency: 'consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'minimal',
    synthesisStatement: 'Extensive multi-centre sham-controlled randomized trials and meta-analyses consistently support 10Hz left DLPFC rTMS for treatment-resistant depression.',
    governanceTierRecommendation: 'A',
  },
  {
    id: 'syn-mdd-002',
    evidenceClaimId: 'clm-mdd-002',
    directness: 'strong',
    replication: 'replicated',
    studyDesignStrength: 'strong',
    sampleSupport: 'strong',
    consistency: 'consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'minimal',
    synthesisStatement: 'A large pivotal non-inferiority randomized trial demonstrated equivalent clinical efficacy between iTBS and standard 10Hz rTMS.',
    governanceTierRecommendation: 'A',
  },
  {
    id: 'syn-mdd-003',
    evidenceClaimId: 'clm-mdd-003',
    directness: 'moderate',
    replication: 'replicated',
    studyDesignStrength: 'moderate',
    sampleSupport: 'moderate',
    consistency: 'mostly_consistent',
    clinicalApplicability: 'partial',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'minimal',
    synthesisStatement: 'Multiple independent prospective and retrospective cohorts confirm that functional anticorrelation with sgACC predicts clinical depression improvement.',
    governanceTierRecommendation: 'B',
  },
  {
    id: 'syn-mdd-004',
    evidenceClaimId: 'clm-mdd-004',
    directness: 'moderate',
    replication: 'replicated',
    studyDesignStrength: 'moderate',
    sampleSupport: 'moderate',
    consistency: 'consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'minimal',
    synthesisStatement: 'Low-frequency 1Hz right DLPFC stimulation is supported by clinical guidelines as an established alternative for treatment-resistant depression.',
    governanceTierRecommendation: 'B',
  },

  // ----------------------------------------------------
  // OCD Syntheses
  // ----------------------------------------------------
  {
    id: 'syn-ocd-001',
    evidenceClaimId: 'clm-ocd-001',
    directness: 'strong',
    replication: 'single_source',
    studyDesignStrength: 'strong',
    sampleSupport: 'moderate',
    consistency: 'consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'material',
    synthesisStatement: 'A pivotal multicentre sham-controlled trial and FDA De Novo clearance support deep-TMS mPFC/ACC field stimulation when combined with symptom provocation.',
    governanceTierRecommendation: 'B',
  },
  {
    id: 'syn-ocd-002',
    evidenceClaimId: 'clm-ocd-002',
    directness: 'moderate',
    replication: 'multiple_independent',
    studyDesignStrength: 'moderate',
    sampleSupport: 'moderate',
    consistency: 'mostly_consistent',
    clinicalApplicability: 'partial',
    targetSpecificity: 'moderate',
    treatmentContextDependence: 'possible',
    synthesisStatement: 'Network meta-analysis supports efficacy across bilateral DLPFC, SMA, and mPFC/ACC without conclusive superiority for any single target family.',
    governanceTierRecommendation: 'B',
  },
  {
    id: 'syn-ocd-003',
    evidenceClaimId: 'clm-ocd-003',
    directness: 'moderate',
    replication: 'replicated',
    studyDesignStrength: 'moderate',
    sampleSupport: 'strong',
    consistency: 'mixed',
    clinicalApplicability: 'partial',
    targetSpecificity: 'moderate',
    treatmentContextDependence: 'possible',
    synthesisStatement: 'Updated meta-analytic evidence confirms statistically significant symptom reduction for DLPFC and mPFC/ACC, though clinical meaningfulness requires scrutiny.',
    governanceTierRecommendation: 'B',
  },
  {
    id: 'syn-ocd-004',
    evidenceClaimId: 'clm-ocd-004',
    directness: 'strong',
    replication: 'replicated',
    studyDesignStrength: 'moderate',
    sampleSupport: 'moderate',
    consistency: 'mostly_negative',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'material',
    synthesisStatement: 'Meta-analysis indicates that low-frequency unnavigated surface-coil rTMS does not produce statistically significant pooled benefit over sham.',
    governanceTierRecommendation: 'D',
  },

  // ----------------------------------------------------
  // Neuropathic Pain Syntheses
  // ----------------------------------------------------
  {
    id: 'syn-pain-001',
    evidenceClaimId: 'clm-pain-001',
    directness: 'strong',
    replication: 'multiple_independent',
    studyDesignStrength: 'strong',
    sampleSupport: 'moderate',
    consistency: 'consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'material',
    synthesisStatement: 'High-frequency contralateral somatotopic M1 rTMS is supported by replicated double-blind sham-controlled trials and international Level A recommendations.',
    governanceTierRecommendation: 'A',
  },
  {
    id: 'syn-pain-002',
    evidenceClaimId: 'clm-pain-002',
    directness: 'moderate',
    replication: 'multiple_independent',
    studyDesignStrength: 'moderate',
    sampleSupport: 'strong',
    consistency: 'mostly_consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'material',
    synthesisStatement: 'Systematic reviews confirm pooled analgesic superiority over sham with higher effect sizes for navigated and high-frequency paradigms.',
    governanceTierRecommendation: 'B',
  },
  {
    id: 'syn-pain-003',
    evidenceClaimId: 'clm-pain-003',
    directness: 'strong',
    replication: 'replicated',
    studyDesignStrength: 'moderate',
    sampleSupport: 'moderate',
    consistency: 'mixed',
    clinicalApplicability: 'direct',
    targetSpecificity: 'moderate',
    treatmentContextDependence: 'minimal',
    synthesisStatement: 'Methodological reviews emphasize substantial heterogeneity, transient benefit duration, and lower certainty in non-navigated peripheral neuropathy subgroups.',
    governanceTierRecommendation: 'C',
  },
  {
    id: 'syn-pain-004',
    evidenceClaimId: 'clm-pain-004',
    directness: 'moderate',
    replication: 'single_source',
    studyDesignStrength: 'moderate',
    sampleSupport: 'strong',
    consistency: 'consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'material',
    synthesisStatement: 'Clinical practice guidelines position M1 rTMS as a specialized third-line therapy for drug-resistant chronic neuropathic pain.',
    governanceTierRecommendation: 'B',
  },

  // ----------------------------------------------------
  // Stroke Motor Recovery Syntheses
  // ----------------------------------------------------
  {
    id: 'syn-stroke-001',
    evidenceClaimId: 'clm-stroke-001',
    directness: 'strong',
    replication: 'multiple_independent',
    studyDesignStrength: 'strong',
    sampleSupport: 'moderate',
    consistency: 'consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'material',
    synthesisStatement: 'Contralesional 1Hz M1 rTMS in the post-acute subacute recovery window is supported by multiple replicated RCTs and international guidelines (Level A).',
    governanceTierRecommendation: 'A',
  },
  {
    id: 'syn-stroke-002',
    evidenceClaimId: 'clm-stroke-002',
    directness: 'moderate',
    replication: 'replicated',
    studyDesignStrength: 'moderate',
    sampleSupport: 'moderate',
    consistency: 'mostly_consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'material',
    synthesisStatement: 'High-frequency ipsilesional M1 rTMS improves motor recovery in post-acute stroke when primary motor cortex is anatomically preserved.',
    governanceTierRecommendation: 'B',
  },
  {
    id: 'syn-stroke-003',
    evidenceClaimId: 'clm-stroke-003',
    directness: 'strong',
    replication: 'multiple_independent',
    studyDesignStrength: 'strong',
    sampleSupport: 'strong',
    consistency: 'mostly_consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'material',
    synthesisStatement: 'A meta-analysis of 37 low-risk RCTs demonstrates significant upper-limb motor improvements with pronounced stage-dependence (acute/subacute > chronic).',
    governanceTierRecommendation: 'B',
  },
  {
    id: 'syn-stroke-004',
    evidenceClaimId: 'clm-stroke-004',
    directness: 'moderate',
    replication: 'replicated',
    studyDesignStrength: 'moderate',
    sampleSupport: 'limited',
    consistency: 'consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'minimal',
    synthesisStatement: 'Mechanistic and clinical studies establish that severe corticospinal injury shifts motor control toward compensatory contralesional recruitment, invalidating contralesional inhibition.',
    governanceTierRecommendation: 'C',
  },

  // ----------------------------------------------------
  // Post-Stroke Aphasia Syntheses
  // ----------------------------------------------------
  {
    id: 'syn-psa-001',
    evidenceClaimId: 'clm-psa-001',
    directness: 'strong',
    replication: 'multiple_independent',
    studyDesignStrength: 'strong',
    sampleSupport: 'moderate',
    consistency: 'consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'material',
    synthesisStatement: 'Replicated randomized sham-controlled trials and international guidelines support 1Hz right IFG rTMS for chronic non-fluent post-stroke aphasia.',
    governanceTierRecommendation: 'B',
  },
  {
    id: 'syn-psa-002',
    evidenceClaimId: 'clm-psa-002',
    directness: 'strong',
    replication: 'multiple_independent',
    studyDesignStrength: 'strong',
    sampleSupport: 'strong',
    consistency: 'consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'material',
    synthesisStatement: 'Meta-analysis of 30 RCTs proves that rTMS combined with concurrent speech-language therapy significantly improves naming, comprehension, and repetition compared with speech therapy alone.',
    governanceTierRecommendation: 'B',
  },
  {
    id: 'syn-psa-003',
    evidenceClaimId: 'clm-psa-003',
    directness: 'moderate',
    replication: 'replicated',
    studyDesignStrength: 'moderate',
    sampleSupport: 'strong',
    consistency: 'mostly_consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'moderate',
    treatmentContextDependence: 'material',
    synthesisStatement: 'Updated meta-analysis of 26 trials reinforces language recovery benefits while highlighting chronicity and individualised stereotaxic navigation as primary moderators.',
    governanceTierRecommendation: 'B',
  },
  {
    id: 'syn-psa-004',
    evidenceClaimId: 'clm-psa-004',
    directness: 'moderate',
    replication: 'replicated',
    studyDesignStrength: 'moderate',
    sampleSupport: 'moderate',
    consistency: 'mixed',
    clinicalApplicability: 'partial',
    targetSpecificity: 'moderate',
    treatmentContextDependence: 'material',
    synthesisStatement: 'Network meta-analysis reveals protocol-dependent ranking variations across immediate vs durable outcomes, disproving a single universal best aphasia protocol.',
    governanceTierRecommendation: 'C',
  },

  // ----------------------------------------------------
  // Traumatic Brain Injury (TBI) Syntheses
  // ----------------------------------------------------
  {
    id: 'syn-tbi-001',
    evidenceClaimId: 'clm-tbi-001',
    directness: 'moderate',
    replication: 'single_source',
    studyDesignStrength: 'moderate',
    sampleSupport: 'limited',
    consistency: 'mixed',
    clinicalApplicability: 'partial',
    targetSpecificity: 'uncertain',
    treatmentContextDependence: 'unknown',
    synthesisStatement: 'Pooled randomized trials report positive cognitive signal post-TBI, but underlying trial targets are heterogeneous and require primary-study extraction.',
    governanceTierRecommendation: 'C',
  },
  {
    id: 'syn-tbi-002',
    evidenceClaimId: 'clm-tbi-002',
    directness: 'moderate',
    replication: 'single_source',
    studyDesignStrength: 'moderate',
    sampleSupport: 'limited',
    consistency: 'mostly_consistent',
    clinicalApplicability: 'partial',
    targetSpecificity: 'uncertain',
    treatmentContextDependence: 'unknown',
    synthesisStatement: 'Randomized evidence shows post-traumatic headache and central pain reductions, but target-family mapping remains unverified.',
    governanceTierRecommendation: 'C',
  },
  {
    id: 'syn-tbi-003',
    evidenceClaimId: 'clm-tbi-003',
    directness: 'moderate',
    replication: 'single_source',
    studyDesignStrength: 'moderate',
    sampleSupport: 'limited',
    consistency: 'mostly_negative',
    clinicalApplicability: 'partial',
    targetSpecificity: 'uncertain',
    treatmentContextDependence: 'unknown',
    synthesisStatement: 'The 2025 meta-analysis found no significant difference over sham for post-TBI depressive symptoms.',
    governanceTierRecommendation: 'D',
  },
  {
    id: 'syn-tbi-004',
    evidenceClaimId: 'clm-tbi-004',
    directness: 'moderate',
    replication: 'single_source',
    studyDesignStrength: 'limited',
    sampleSupport: 'limited',
    consistency: 'mixed',
    clinicalApplicability: 'partial',
    targetSpecificity: 'moderate',
    treatmentContextDependence: 'unknown',
    synthesisStatement: 'Earlier systematic review found short-term benefit for depression in TBI, but long-term durability is unverified.',
    governanceTierRecommendation: 'D',
  },
  {
    id: 'syn-tbi-005',
    evidenceClaimId: 'clm-tbi-005',
    directness: 'strong',
    replication: 'replicated',
    studyDesignStrength: 'strong',
    sampleSupport: 'limited',
    consistency: 'mostly_negative',
    clinicalApplicability: 'direct',
    targetSpecificity: 'uncertain',
    treatmentContextDependence: 'unknown',
    synthesisStatement: 'Trial sequential analysis concluded that the available randomized evidence base is underpowered and insufficient to establish benefit in TBI.',
    governanceTierRecommendation: 'D',
  },

  // ----------------------------------------------------
  // PTSD Syntheses
  // ----------------------------------------------------
  {
    id: 'syn-ptsd-001',
    evidenceClaimId: 'clm-ptsd-001',
    directness: 'strong',
    replication: 'multiple_independent',
    studyDesignStrength: 'strong',
    sampleSupport: 'moderate',
    consistency: 'consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'minimal',
    synthesisStatement: 'Replicated sham-controlled RCTs and international guidelines (Level B) support high-frequency right-DLPFC rTMS for core symptom reduction in civilian PTSD.',
    governanceTierRecommendation: 'B',
  },
  {
    id: 'syn-ptsd-002',
    evidenceClaimId: 'clm-ptsd-002',
    directness: 'moderate',
    replication: 'replicated',
    studyDesignStrength: 'moderate',
    sampleSupport: 'moderate',
    consistency: 'mostly_consistent',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'minimal',
    synthesisStatement: 'Systematic reviews confirm sham-controlled symptom improvements with post-treatment durability in general trauma cohorts.',
    governanceTierRecommendation: 'B',
  },
  {
    id: 'syn-ptsd-003',
    evidenceClaimId: 'clm-ptsd-003',
    directness: 'moderate',
    replication: 'replicated',
    studyDesignStrength: 'moderate',
    sampleSupport: 'moderate',
    consistency: 'mostly_consistent',
    clinicalApplicability: 'partial',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'minimal',
    synthesisStatement: 'Comparative network meta-analysis demonstrates that high-frequency right DLPFC is the most efficacious target strategy for PTSD.',
    governanceTierRecommendation: 'B',
  },
  {
    id: 'syn-ptsd-004',
    evidenceClaimId: 'clm-ptsd-004',
    directness: 'strong',
    replication: 'replicated',
    studyDesignStrength: 'strong',
    sampleSupport: 'moderate',
    consistency: 'mostly_negative',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'minimal',
    synthesisStatement: 'Meta-analysis restricted to combat-exposed veteran PTSD found high sham response rates and no statistically significant active-versus-sham pooled difference.',
    governanceTierRecommendation: 'C',
  },

  // ----------------------------------------------------
  // Tinnitus Syntheses
  // ----------------------------------------------------
  {
    id: 'syn-tin-001',
    evidenceClaimId: 'clm-tin-001',
    directness: 'strong',
    replication: 'single_source',
    studyDesignStrength: 'strong',
    sampleSupport: 'strong',
    consistency: 'mostly_negative',
    clinicalApplicability: 'direct',
    targetSpecificity: 'broad',
    treatmentContextDependence: 'minimal',
    synthesisStatement: 'The AAO-HNS expert clinical guideline recommends against routine rTMS for persistent bothersome tinnitus due to unfavorable risk-benefit.',
    governanceTierRecommendation: 'D',
  },
  {
    id: 'syn-tin-002',
    evidenceClaimId: 'clm-tin-002',
    directness: 'strong',
    replication: 'multiple_independent',
    studyDesignStrength: 'strong',
    sampleSupport: 'moderate',
    consistency: 'mostly_negative',
    clinicalApplicability: 'direct',
    targetSpecificity: 'specific',
    treatmentContextDependence: 'minimal',
    synthesisStatement: 'Ten randomized trials and the multicentre TRI trial demonstrated non-significant pooled efficacy of 1Hz temporoparietal rTMS over sham on THI and TQ.',
    governanceTierRecommendation: 'D',
  },
  {
    id: 'syn-tin-003',
    evidenceClaimId: 'clm-tin-003',
    directness: 'moderate',
    replication: 'replicated',
    studyDesignStrength: 'moderate',
    sampleSupport: 'moderate',
    consistency: 'mixed',
    clinicalApplicability: 'partial',
    targetSpecificity: 'moderate',
    treatmentContextDependence: 'minimal',
    synthesisStatement: 'Pooled randomized evidence reveals modest short-term reduction in tinnitus distress that attenuates to non-significance by 6 months post-treatment.',
    governanceTierRecommendation: 'C',
  },
  {
    id: 'syn-tin-004',
    evidenceClaimId: 'clm-tin-004',
    directness: 'strong',
    replication: 'replicated',
    studyDesignStrength: 'strong',
    sampleSupport: 'moderate',
    consistency: 'mostly_negative',
    clinicalApplicability: 'direct',
    targetSpecificity: 'moderate',
    treatmentContextDependence: 'minimal',
    synthesisStatement: 'A comprehensive 2026 systematic review found no statistically significant benefit in robust double-blind trials, supporting research-only classification.',
    governanceTierRecommendation: 'D',
  },
  {
    id: 'syn-tin-005',
    evidenceClaimId: 'clm-tin-005',
    directness: 'moderate',
    replication: 'single_source',
    studyDesignStrength: 'moderate',
    sampleSupport: 'moderate',
    consistency: 'mixed',
    clinicalApplicability: 'partial',
    targetSpecificity: 'moderate',
    treatmentContextDependence: 'minimal',
    synthesisStatement: 'Recent meta-analysis indicates modest immediate THI gains with high heterogeneity, reinforcing that tinnitus rTMS remains an unresolved research problem.',
    governanceTierRecommendation: 'C',
  },
];
