/**
 * Canonical TargetFamily v2 Seeds
 * Conforms to MAGNIOM-Evidence Knowledge Graph & Therapeutic Circuit Library v2.0
 * (§13, §18, §24, §31, §37, §44, §50, §58, §65, §83, §84, §85, §86)
 */

import type { TargetFamilyV2 } from '@magniom/domain';

export const CANONICAL_TARGET_FAMILIES_V2: readonly TargetFamilyV2[] = [
  // ----------------------------------------------------
  // MDD Target Families (Clinical Permitted via v1 Migration §106)
  // ----------------------------------------------------
  {
    id: 'TF-MDD-LDLPFC-001',
    code: 'TF-MDD-CONVERGENT-LDLPFC-001',
    version: '2.0.0',
    name: 'Left DLPFC Convergent Target Family (BA46 / SGC Anticorrelation)',
    hemisphere: 'L',
    primaryHcpParcel: 'L_p9-46v',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: -44, y: 40, z: 28, unit: 'mm' },
    maxAllowableDisplacementMm: 12.0,
    evidenceCeilingTier: 'T1',
    governanceStatus: 'clinical_permitted',
    permittedTargetGeometryTypes: ['point', 'surface_roi'],
    permittedGeometryTypes: ['point', 'surface_roi'],
    indicationScopeIds: ['ind-mdd-001'],
    indicationModuleReleaseId: 'mod-mdd-rel-200',
    clinicalObjectiveDefinitionIds: ['obj-mdd-core-001', 'obj-mdd-remission-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000001'],
    evidenceClaimIds: ['clm-mdd-001', 'clm-mdd-002', 'clm-mdd-003'],
    candidateGenerationMethodIds: ['gen-fmri-sgc-anticorr', 'gen-beam-f3-fallback'],
    limitations: ['Requires structural T1w for neuronavigation precision.'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'tf-mdd-001',
    code: 'TF-MDD-CONVERGENT-LDLPFC-001',
    version: '2.0.0',
    name: 'Left DLPFC Convergent Target Family (BA46 / SGC Anticorrelation)',
    hemisphere: 'L',
    primaryHcpParcel: 'L_p9-46v',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: -44, y: 40, z: 28, unit: 'mm' },
    maxAllowableDisplacementMm: 12.0,
    evidenceCeilingTier: 'T1',
    governanceStatus: 'clinical_permitted',
    permittedTargetGeometryTypes: ['point', 'surface_roi'],
    permittedGeometryTypes: ['point', 'surface_roi'],
    indicationScopeIds: ['ind-mdd-001'],
    indicationModuleReleaseId: 'mod-mdd-rel-200',
    clinicalObjectiveDefinitionIds: ['obj-mdd-core-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000001'],
    evidenceClaimIds: ['clm-mdd-001', 'clm-mdd-002'],
    candidateGenerationMethodIds: ['gen-fmri-sgc-anticorr', 'gen-beam-f3-fallback'],
    limitations: ['Requires structural T1w for neuronavigation precision.'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'TF-MDD-RDLPFC-001',
    code: 'TF-MDD-DORSAL-BA9-001',
    version: '2.0.0',
    name: 'Right DLPFC Inhibitory Target Family (Low Frequency)',
    hemisphere: 'R',
    primaryHcpParcel: 'R_9a',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: 38, y: 32, z: 46, unit: 'mm' },
    maxAllowableDisplacementMm: 15.0,
    evidenceCeilingTier: 'T2',
    governanceStatus: 'clinical_permitted',
    permittedTargetGeometryTypes: ['point'],
    permittedGeometryTypes: ['point'],
    indicationScopeIds: ['ind-mdd-001'],
    indicationModuleReleaseId: 'mod-mdd-rel-200',
    clinicalObjectiveDefinitionIds: ['obj-mdd-response-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000001'],
    evidenceClaimIds: ['clm-mdd-004'],
    candidateGenerationMethodIds: ['gen-structural-landmark'],
    limitations: ['Secondary clinical alternative.'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'tf-mdd-002',
    code: 'TF-MDD-ANTERIOR-LDLPFC-001',
    version: '2.0.0',
    name: 'Left DLPFC Anterior Target Family (BA46/10)',
    hemisphere: 'L',
    primaryHcpParcel: 'L_46',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: -40, y: 48, z: 22, unit: 'mm' },
    maxAllowableDisplacementMm: 12.0,
    evidenceCeilingTier: 'T2',
    governanceStatus: 'clinical_permitted',
    permittedTargetGeometryTypes: ['point', 'surface_roi'],
    permittedGeometryTypes: ['point', 'surface_roi'],
    indicationScopeIds: ['ind-mdd-001'],
    indicationModuleReleaseId: 'mod-mdd-rel-200',
    clinicalObjectiveDefinitionIds: ['obj-mdd-core-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000001'],
    evidenceClaimIds: ['clm-mdd-002'],
    candidateGenerationMethodIds: ['gen-beam-f3-fallback'],
    limitations: ['Secondary anatomical alternative.'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'tf-mdd-003',
    code: 'TF-MDD-DORSAL-BA9-001',
    version: '2.0.0',
    name: 'Left DLPFC Dorsal Target Family (BA9/8Av)',
    hemisphere: 'L',
    primaryHcpParcel: 'L_9a',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: -38, y: 32, z: 46, unit: 'mm' },
    maxAllowableDisplacementMm: 15.0,
    evidenceCeilingTier: 'T3',
    governanceStatus: 'clinical_permitted',
    permittedTargetGeometryTypes: ['point'],
    permittedGeometryTypes: ['point'],
    indicationScopeIds: ['ind-mdd-001'],
    indicationModuleReleaseId: 'mod-mdd-rel-200',
    clinicalObjectiveDefinitionIds: ['obj-mdd-core-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000001'],
    evidenceClaimIds: ['clm-mdd-004'],
    candidateGenerationMethodIds: ['gen-structural-landmark'],
    limitations: ['Anatomical landmark baseline only.'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },

  // ----------------------------------------------------
  // OCD Target Families (§24, §83)
  // ----------------------------------------------------
  {
    id: 'TF-OCD-MPFC-ACC-FIELD-001',
    code: 'TF-OCD-MPFC-ACC-FIELD-001',
    version: '2.0.0',
    name: 'Medial Prefrontal / Anterior Cingulate Deep TMS Field Target',
    hemisphere: 'BILATERAL',
    primaryHcpParcel: 'L_d32_R_d32',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: 0, y: 35, z: 25, unit: 'mm' },
    maxAllowableDisplacementMm: 20.0,
    evidenceCeilingTier: 'T1',
    governanceStatus: 'staging',
    permittedTargetGeometryTypes: ['coil_field'],
    permittedGeometryTypes: ['coil_field'],
    indicationScopeIds: ['ind-ocd-001'],
    indicationModuleReleaseId: 'mod-ocd-rel-staging',
    clinicalObjectiveDefinitionIds: ['obj-ocd-core-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000002'],
    evidenceClaimIds: ['clm-ocd-001', 'clm-ocd-002'],
    candidateGenerationMethodIds: ['gen-ocd-h7-field'],
    treatmentContextRequirementIds: ['ctx-ocd-provocation-001'],
    limitations: [
      'Pivotal efficacy established with H7 coil field; does not validate point-coordinate focal coils (§26, §83).',
    ],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'TF-OCD-PRESMA-SMA-001',
    code: 'TF-OCD-PRESMA-SMA-001',
    version: '2.0.0',
    name: 'Supplementary Motor Area / Pre-SMA Target Family',
    hemisphere: 'BILATERAL',
    primaryHcpParcel: 'L_SFL_R_SFL',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: 0, y: 15, z: 58, unit: 'mm' },
    maxAllowableDisplacementMm: 15.0,
    evidenceCeilingTier: 'T2',
    governanceStatus: 'staging',
    permittedTargetGeometryTypes: ['surface_roi', 'point'],
    permittedGeometryTypes: ['surface_roi', 'point'],
    indicationScopeIds: ['ind-ocd-001'],
    indicationModuleReleaseId: 'mod-ocd-rel-staging',
    clinicalObjectiveDefinitionIds: ['obj-ocd-core-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000002'],
    evidenceClaimIds: ['clm-ocd-002'],
    candidateGenerationMethodIds: ['gen-sma-anatomical'],
    limitations: ['Heterogeneous sham-controlled effect sizes across surface coils.'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'TF-OCD-DLPFC-001',
    code: 'TF-OCD-DLPFC-001',
    version: '2.0.0',
    name: 'Bilateral / Right DLPFC Target Family for OCD',
    hemisphere: 'BILATERAL',
    primaryHcpParcel: 'R_9-46d',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: 44, y: 38, z: 32, unit: 'mm' },
    maxAllowableDisplacementMm: 15.0,
    evidenceCeilingTier: 'T2',
    governanceStatus: 'staging',
    permittedTargetGeometryTypes: ['point', 'surface_roi'],
    permittedGeometryTypes: ['point', 'surface_roi'],
    indicationScopeIds: ['ind-ocd-001'],
    indicationModuleReleaseId: 'mod-ocd-rel-staging',
    clinicalObjectiveDefinitionIds: ['obj-ocd-core-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000002'],
    evidenceClaimIds: ['clm-ocd-003'],
    candidateGenerationMethodIds: ['gen-ocd-dlpfc-grid'],
    limitations: ['Competes with mPFC/ACC; no single universally superior target (§27).'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'TF-OCD-OFC-001',
    code: 'TF-OCD-OFC-001',
    version: '2.0.0',
    name: 'Orbitofrontal Cortex Target Family for OCD',
    hemisphere: 'R',
    primaryHcpParcel: 'R_OFC',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: 28, y: 36, z: -12, unit: 'mm' },
    maxAllowableDisplacementMm: 12.0,
    evidenceCeilingTier: 'T3',
    governanceStatus: 'staging',
    permittedTargetGeometryTypes: ['point'],
    permittedGeometryTypes: ['point'],
    indicationScopeIds: ['ind-ocd-001'],
    indicationModuleReleaseId: 'mod-ocd-rel-staging',
    clinicalObjectiveDefinitionIds: ['obj-ocd-core-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000002'],
    evidenceClaimIds: ['clm-ocd-002'],
    candidateGenerationMethodIds: ['gen-ofc-deep'],
    limitations: ['Preliminary exploratory clinical data.'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },

  // ----------------------------------------------------
  // Neuropathic Pain Target Families (§31, §84)
  // ----------------------------------------------------
  {
    id: 'TF-PAIN-M1-SOMATO-001',
    code: 'TF-PAIN-M1-SOMATO-001',
    version: '2.0.0',
    name: 'Somatotopic Contralateral Primary Motor Cortex (M1)',
    hemisphere: 'L',
    primaryHcpParcel: 'M1_somatotopic',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: -37, y: -25, z: 58, unit: 'mm' },
    maxAllowableDisplacementMm: 10.0,
    evidenceCeilingTier: 'T1',
    governanceStatus: 'staging',
    permittedTargetGeometryTypes: ['somatotopic'],
    permittedGeometryTypes: ['somatotopic'],
    indicationScopeIds: ['ind-pain-001'],
    indicationModuleReleaseId: 'mod-pain-rel-staging',
    clinicalObjectiveDefinitionIds: ['obj-pain-reduction-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000003'],
    evidenceClaimIds: ['clm-pain-001', 'clm-pain-002'],
    candidateGenerationMethodIds: ['gen-pain-mep-hotspot', 'gen-pain-somatotopic-grid'],
    limitations: [
      'Strict somatotopic requirement: target must be positioned contralateral to painful region (§84).',
      'Guideline Level A does NOT equate to automatic MAGNIOM Tier A (§9, §32).',
    ],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },

  // ----------------------------------------------------
  // Stroke Motor Target Families (§37, §85)
  // ----------------------------------------------------
  {
    id: 'TF-STROKE-MOTOR-CM1-001',
    code: 'TF-STROKE-MOTOR-CM1-001',
    version: '2.0.0',
    name: 'Contralesional Primary Motor Cortex Low-Frequency Target Family',
    hemisphere: 'R',
    primaryHcpParcel: 'M1_hand_knob',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: 38, y: -22, z: 56, unit: 'mm' },
    maxAllowableDisplacementMm: 10.0,
    evidenceCeilingTier: 'T1',
    governanceStatus: 'staging',
    permittedTargetGeometryTypes: ['somatotopic'],
    permittedGeometryTypes: ['somatotopic'],
    indicationScopeIds: ['ind-stroke-001'],
    indicationModuleReleaseId: 'mod-stroke-rel-staging',
    clinicalObjectiveDefinitionIds: ['obj-stroke-ue-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000004'],
    evidenceClaimIds: ['clm-stroke-001'],
    candidateGenerationMethodIds: ['gen-stroke-cm1-hotspot'],
    treatmentContextRequirementIds: ['ctx-stroke-rehab-001'],
    diseaseStageConstraints: ['stg-stroke-subacute-001'],
    limitations: [
      'Subacute stage restriction; severe structural damage requires preservation of contralesional drive (§42, §85).',
    ],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'TF-STROKE-MOTOR-IM1-001',
    code: 'TF-STROKE-MOTOR-IM1-001',
    version: '2.0.0',
    name: 'Ipsilesional Perilesional Primary Motor Cortex High-Frequency Target Family',
    hemisphere: 'L',
    primaryHcpParcel: 'M1_perilesional',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: -36, y: -24, z: 54, unit: 'mm' },
    maxAllowableDisplacementMm: 12.0,
    evidenceCeilingTier: 'T2',
    governanceStatus: 'staging',
    permittedTargetGeometryTypes: ['somatotopic', 'surface_roi'],
    permittedGeometryTypes: ['somatotopic', 'surface_roi'],
    indicationScopeIds: ['ind-stroke-001'],
    indicationModuleReleaseId: 'mod-stroke-rel-staging',
    clinicalObjectiveDefinitionIds: ['obj-stroke-ue-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000004'],
    evidenceClaimIds: ['clm-stroke-002'],
    candidateGenerationMethodIds: ['gen-stroke-im1-perilesional'],
    treatmentContextRequirementIds: ['ctx-stroke-rehab-001'],
    limitations: ['Requires viable surviving corticospinal tract fibers adjacent to lesion.'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'TF-STROKE-MOTOR-SMA-001',
    code: 'TF-STROKE-MOTOR-SMA-001',
    version: '2.0.0',
    name: 'Secondary Motor Cortex (SMA / Pre-SMA) Target Family for Stroke',
    hemisphere: 'BILATERAL',
    primaryHcpParcel: 'SMA',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: 0, y: 4, z: 60, unit: 'mm' },
    maxAllowableDisplacementMm: 15.0,
    evidenceCeilingTier: 'T3',
    governanceStatus: 'staging',
    permittedTargetGeometryTypes: ['surface_roi'],
    permittedGeometryTypes: ['surface_roi'],
    indicationScopeIds: ['ind-stroke-001'],
    indicationModuleReleaseId: 'mod-stroke-rel-staging',
    clinicalObjectiveDefinitionIds: ['obj-stroke-ue-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000004'],
    evidenceClaimIds: ['clm-stroke-003'],
    candidateGenerationMethodIds: ['gen-stroke-secondary-motor'],
    limitations: ['Secondary motor network hypothesis for severe capsular stroke.'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },

  // ----------------------------------------------------
  // Post-Stroke Aphasia Target Families (§44, §86)
  // ----------------------------------------------------
  {
    id: 'TF-PSA-RIFG-001',
    code: 'TF-PSA-RIFG-001',
    version: '2.0.0',
    name: 'Right Inferior Frontal Gyrus (pars triangularis / opercularis) Target Family',
    hemisphere: 'R',
    primaryHcpParcel: 'R_45_44',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: 52, y: 24, z: 12, unit: 'mm' },
    maxAllowableDisplacementMm: 10.0,
    evidenceCeilingTier: 'T1',
    governanceStatus: 'staging',
    permittedTargetGeometryTypes: ['point', 'surface_roi'],
    permittedGeometryTypes: ['point', 'surface_roi'],
    indicationScopeIds: ['ind-aphasia-001'],
    indicationModuleReleaseId: 'mod-aphasia-rel-staging',
    clinicalObjectiveDefinitionIds: ['obj-aphasia-naming-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000005'],
    evidenceClaimIds: ['clm-psa-001'],
    candidateGenerationMethodIds: ['gen-psa-rifg-triangularis'],
    treatmentContextRequirementIds: ['tc-slt-001', 'ctx-psa-slt-001'],
    diseaseStageConstraints: ['stg-stroke-chronic-001'],
    limitations: [
      'Mandatory speech-language therapy context (§86).',
      'Chronic non-fluent post-stroke aphasia population boundary (§47).',
    ],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'TF-PSA-LIFG-001',
    code: 'TF-PSA-LIFG-001',
    version: '2.0.0',
    name: 'Left Perilesional Inferior Frontal Gyrus (Broca) Target Family',
    hemisphere: 'L',
    primaryHcpParcel: 'L_45_44',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: -50, y: 22, z: 14, unit: 'mm' },
    maxAllowableDisplacementMm: 12.0,
    evidenceCeilingTier: 'T2',
    governanceStatus: 'staging',
    permittedTargetGeometryTypes: ['point', 'surface_roi'],
    permittedGeometryTypes: ['point', 'surface_roi'],
    indicationScopeIds: ['ind-aphasia-001'],
    indicationModuleReleaseId: 'mod-aphasia-rel-staging',
    clinicalObjectiveDefinitionIds: ['obj-aphasia-naming-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000005'],
    evidenceClaimIds: ['clm-psa-002'],
    candidateGenerationMethodIds: ['gen-psa-lifg-perilesional'],
    treatmentContextRequirementIds: ['tc-slt-001', 'ctx-psa-slt-001'],
    limitations: ['Requires residual intact cortex in left frontal language network.'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'TF-PSA-BILAT-WERNICKE-001',
    code: 'TF-PSA-BILAT-WERNICKE-001',
    version: '2.0.0',
    name: 'Superior Temporal Gyrus (Wernicke / Posterior STG) Target Family',
    hemisphere: 'BILATERAL',
    primaryHcpParcel: 'A4',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: 58, y: -42, z: 12, unit: 'mm' },
    maxAllowableDisplacementMm: 15.0,
    evidenceCeilingTier: 'T3',
    governanceStatus: 'staging',
    permittedTargetGeometryTypes: ['point'],
    permittedGeometryTypes: ['point'],
    indicationScopeIds: ['ind-aphasia-001'],
    indicationModuleReleaseId: 'mod-aphasia-rel-staging',
    clinicalObjectiveDefinitionIds: ['obj-aphasia-comm-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000005'],
    evidenceClaimIds: ['clm-psa-003'],
    candidateGenerationMethodIds: ['gen-psa-stg-receptive'],
    treatmentContextRequirementIds: ['tc-slt-001', 'ctx-psa-slt-001'],
    limitations: ['Preliminary evidence focused on auditory comprehension sub-scores.'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },

  // ----------------------------------------------------
  // TBI Target Families (§50, §87)
  // ----------------------------------------------------
  {
    id: 'TF-TBI-DLPFC-001',
    code: 'TF-TBI-DLPFC-001',
    version: '2.0.0',
    name: 'TBI Exploratory Dorsolateral Prefrontal Cortex Target Family',
    hemisphere: 'L',
    primaryHcpParcel: 'L_9-46d',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: -42, y: 36, z: 30, unit: 'mm' },
    maxAllowableDisplacementMm: 15.0,
    evidenceCeilingTier: 'T3',
    governanceStatus: 'research',
    permittedTargetGeometryTypes: ['surface_roi', 'point'],
    permittedGeometryTypes: ['surface_roi', 'point'],
    indicationScopeIds: ['ind-tbi-001'],
    indicationModuleReleaseId: 'mod-tbi-rel-staging',
    clinicalObjectiveDefinitionIds: ['obj-tbi-cog-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000006'],
    evidenceClaimIds: ['clm-tbi-001'],
    candidateGenerationMethodIds: ['gen-tbi-research-dlpfc'],
    limitations: [
      'Missing target specificity across trials: literature uses heterogeneous 5cm/F3 without coordinates (§50).',
      'Research-only staging status (§50, §87); no Clinical promotion permitted.',
    ],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },

  // ----------------------------------------------------
  // PTSD Target Families (§58, §88)
  // ----------------------------------------------------
  {
    id: 'TF-PTSD-RDLPFC-001',
    code: 'TF-PTSD-RDLPFC-001',
    version: '2.0.0',
    name: 'Right DLPFC High-Frequency Fronto-Limbic Target Family',
    hemisphere: 'R',
    primaryHcpParcel: 'R_9-46d',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: 42, y: 38, z: 30, unit: 'mm' },
    maxAllowableDisplacementMm: 12.0,
    evidenceCeilingTier: 'T1',
    governanceStatus: 'staging',
    permittedTargetGeometryTypes: ['point', 'surface_roi'],
    permittedGeometryTypes: ['point', 'surface_roi'],
    indicationScopeIds: ['ind-ptsd-001'],
    indicationModuleReleaseId: 'mod-ptsd-rel-staging',
    clinicalObjectiveDefinitionIds: ['obj-ptsd-core-001', 'obj-ptsd-hyperarousal-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000007'],
    evidenceClaimIds: ['clm-ptsd-001'],
    candidateGenerationMethodIds: ['gen-ptsd-rdlpfc-beam'],
    limitations: [
      'Civilian evidence does NOT automatically transfer to combat-related trauma populations (§88).',
    ],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'TF-PTSD-LDLPFC-001',
    code: 'TF-PTSD-LDLPFC-001',
    version: '2.0.0',
    name: 'Left DLPFC Sequential / Comorbid Target Family for PTSD',
    hemisphere: 'L',
    primaryHcpParcel: 'L_p9-46v',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: -44, y: 38, z: 28, unit: 'mm' },
    maxAllowableDisplacementMm: 12.0,
    evidenceCeilingTier: 'T2',
    governanceStatus: 'staging',
    permittedTargetGeometryTypes: ['point', 'surface_roi'],
    permittedGeometryTypes: ['point', 'surface_roi'],
    indicationScopeIds: ['ind-ptsd-001'],
    indicationModuleReleaseId: 'mod-ptsd-rel-staging',
    clinicalObjectiveDefinitionIds: ['obj-ptsd-core-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000007'],
    evidenceClaimIds: ['clm-ptsd-003'],
    candidateGenerationMethodIds: ['gen-ptsd-ldlpfc-comorbid'],
    limitations: ['Secondary hypothesis addressing comorbid major depressive episodes.'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },

  // ----------------------------------------------------
  // Tinnitus Target Families (§65, §89, §100)
  // NOTE: Research Only Staging Posture! Zero Clinical Permission!
  // ----------------------------------------------------
  {
    id: 'TF-TIN-TEMPORAL-001',
    code: 'TF-TIN-TEMPORAL-AUDITORY-001',
    version: '2.0.0',
    name: 'Primary / Secondary Auditory Cortex Research Target Family (A1 / Heschl / STG)',
    hemisphere: 'L',
    primaryHcpParcel: 'A1_Heschl',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: -56, y: -24, z: 8, unit: 'mm' },
    maxAllowableDisplacementMm: 12.0,
    evidenceCeilingTier: 'T2',
    governanceStatus: 'research',
    permittedTargetGeometryTypes: ['surface_roi', 'point'],
    permittedGeometryTypes: ['surface_roi', 'point'],
    indicationScopeIds: ['ind-tinnitus-001'],
    indicationModuleReleaseId: 'mod-tinnitus-rel-research',
    clinicalObjectiveDefinitionIds: ['obj-tin-distress-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000008'],
    evidenceClaimIds: ['clm-tin-001', 'clm-tin-003'],
    candidateGenerationMethodIds: ['gen-tin-a1-research'],
    limitations: [
      'Material negative guideline recommendation against routine use (§66, §89).',
      'Research-permitted status only; clinical candidate generation strictly prohibited (§71, §100).',
    ],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'TF-TIN-TEMPORAL-AUDITORY-001',
    code: 'TF-TIN-TEMPORAL-AUDITORY-001',
    version: '2.0.0',
    name: 'Primary / Secondary Auditory Cortex Research Target Family (A1 / Heschl / STG)',
    hemisphere: 'L',
    primaryHcpParcel: 'A1_Heschl',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: -56, y: -24, z: 8, unit: 'mm' },
    maxAllowableDisplacementMm: 12.0,
    evidenceCeilingTier: 'T2',
    governanceStatus: 'research',
    permittedTargetGeometryTypes: ['surface_roi', 'point'],
    permittedGeometryTypes: ['surface_roi', 'point'],
    indicationScopeIds: ['ind-tinnitus-001'],
    indicationModuleReleaseId: 'mod-tinnitus-rel-research',
    clinicalObjectiveDefinitionIds: ['obj-tin-distress-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000008'],
    evidenceClaimIds: ['clm-tin-001', 'clm-tin-003'],
    candidateGenerationMethodIds: ['gen-tin-a1-research'],
    limitations: [
      'Material negative guideline recommendation against routine use (§66, §89).',
      'Research-permitted status only; clinical candidate generation strictly prohibited (§71, §100).',
    ],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'TF-TIN-TPJ-001',
    code: 'TF-TIN-TEMPOROPARIETAL-001',
    version: '2.0.0',
    name: 'Left Temporoparietal Junction (TP3 / CP6) Research Target Family',
    hemisphere: 'L',
    primaryHcpParcel: 'TPJ',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: -62, y: -38, z: 20, unit: 'mm' },
    maxAllowableDisplacementMm: 15.0,
    evidenceCeilingTier: 'T2',
    governanceStatus: 'research',
    permittedTargetGeometryTypes: ['point', 'surface_roi'],
    permittedGeometryTypes: ['point', 'surface_roi'],
    indicationScopeIds: ['ind-tinnitus-001'],
    indicationModuleReleaseId: 'mod-tinnitus-rel-research',
    clinicalObjectiveDefinitionIds: ['obj-tin-distress-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000008'],
    evidenceClaimIds: ['clm-tin-001', 'clm-tin-004'],
    candidateGenerationMethodIds: ['gen-tin-tpj-research'],
    limitations: ['Conflicting meta-analytic outcomes; research mode only.'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'TF-TIN-TEMPOROPARIETAL-001',
    code: 'TF-TIN-TEMPOROPARIETAL-001',
    version: '2.0.0',
    name: 'Left Temporoparietal Junction (TP3 / CP6) Research Target Family',
    hemisphere: 'L',
    primaryHcpParcel: 'TPJ',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: -62, y: -38, z: 20, unit: 'mm' },
    maxAllowableDisplacementMm: 15.0,
    evidenceCeilingTier: 'T2',
    governanceStatus: 'research',
    permittedTargetGeometryTypes: ['point', 'surface_roi'],
    permittedGeometryTypes: ['point', 'surface_roi'],
    indicationScopeIds: ['ind-tinnitus-001'],
    indicationModuleReleaseId: 'mod-tinnitus-rel-research',
    clinicalObjectiveDefinitionIds: ['obj-tin-distress-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000008'],
    evidenceClaimIds: ['clm-tin-001', 'clm-tin-004'],
    candidateGenerationMethodIds: ['gen-tin-tpj-research'],
    limitations: ['Conflicting meta-analytic outcomes; research mode only.'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
  {
    id: 'TF-TIN-COMBINED-001',
    code: 'TF-TIN-COMBINED-001',
    version: '2.0.0',
    name: 'Dual-Site Prefrontal-Temporal Auditory Research Target Family',
    hemisphere: 'BILATERAL',
    primaryHcpParcel: 'Combined_DLPFC_A1',
    fallbackMniCoordinate: { space: 'MNI152NLin2009cAsym', x: -44, y: 38, z: 28, unit: 'mm' },
    maxAllowableDisplacementMm: 20.0,
    evidenceCeilingTier: 'T3',
    governanceStatus: 'research',
    permittedTargetGeometryTypes: ['surface_roi'],
    permittedGeometryTypes: ['surface_roi'],
    indicationScopeIds: ['ind-tinnitus-001'],
    indicationModuleReleaseId: 'mod-tinnitus-rel-research',
    clinicalObjectiveDefinitionIds: ['obj-tin-distress-001'],
    therapeuticCircuitIds: ['c0000000-0000-0000-0001-000000000008'],
    evidenceClaimIds: ['clm-tin-005'],
    candidateGenerationMethodIds: ['gen-tin-dual-site-research'],
    limitations: ['Exploratory dual-site multi-coil protocol; non-significant in recent 2026 meta-analysis.'],
    provenance: {
      createdBy: 'magniom_scientific_curation',
      createdAt: '2026-09-02T00:00:00Z',
      softwareVersion: '2.0.0',
    },
  },
];
